insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Chris Morris', TwitterScreenName='_ChrisMorris', TwitterUserID='95148130', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Adam Blenford', TwitterScreenName='adamblenford', TwitterUserID='9442262', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Alistair Burnett', TwitterScreenName='afburnett', TwitterUserID='277570942', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Aleem Maqbool', TwitterScreenName='AleemMaqbool', TwitterUserID='135162675', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Alastair Leithead', TwitterScreenName='aleithead', TwitterUserID='47854857', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Allan Little', TwitterScreenName='alittl', TwitterUserID='318420468', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='alex baxter', TwitterScreenName='alxbaxter', TwitterUserID='108346847', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Andrew Benson', TwitterScreenName='andrewbensonf1', TwitterUserID='58444150', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Andy Dangerfield', TwitterScreenName='andydangerfield', TwitterUserID='23240010', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Andrew Verity', TwitterScreenName='andyverity', TwitterUserID='274472153', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Anna Adams', TwitterScreenName='AnnaAdamsBBC', TwitterUserID='50284910', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='anna holligan', TwitterScreenName='annaholligan', TwitterUserID='19103793', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='anna williams', TwitterScreenName='Annajsays', TwitterUserID='31479008', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='natalia antelava', TwitterScreenName='antelavan', TwitterUserID='118313302', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Anthony Bartram', TwitterScreenName='AnthonyBartram', TwitterUserID='146097385', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Arif Ansari', TwitterScreenName='ArifBBC', TwitterUserID='92795930', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Babita Sharma', TwitterScreenName='BabitaBBC', TwitterUserID='264224758', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Vladimir Hernandez', TwitterScreenName='bbc_hernandez', TwitterUserID='143077880', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Joe Lynam BBC Biz', TwitterScreenName='BBC_Joe_Lynam', TwitterUserID='20178144', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='BBC 2012', TwitterScreenName='bbc2012', TwitterUserID='156242287', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='George Alagiah', TwitterScreenName='BBCAlagiah', TwitterUserID='111310036', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Allegra Stratton', TwitterScreenName='BBCAllegra', TwitterUserID='492285158', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Jonathan Amos', TwitterScreenName='BBCAmos', TwitterUserID='104585489', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Andrew Black', TwitterScreenName='BBCAndrewBlack', TwitterUserID='305560674', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='andrew harding', TwitterScreenName='BBCAndrewH', TwitterUserID='132195390', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Barbara Plett', TwitterScreenName='BBCBarbaraPlett', TwitterUserID='125656811', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Ben Wright', TwitterScreenName='BBCBenWright', TwitterUserID='226146962', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Chris McLaughlin', TwitterScreenName='BBCchrismclaug', TwitterUserID='205665364', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Daniel Sandford', TwitterScreenName='BBCDanielS', TwitterUserID='331658004', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='david eades', TwitterScreenName='BBCDavidEades', TwitterUserID='116798290', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='David Miller', TwitterScreenName='BBCDavidMiller', TwitterUserID='21917984', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Dominic Casciani', TwitterScreenName='BBCDomC', TwitterUserID='399933', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Douglas Fraser', TwitterScreenName='BBCDouglsFraser', TwitterUserID='129837660', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Emma Simpson', TwitterScreenName='BBCEmmaSimpson', TwitterUserID='235180806', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Fergus Walsh', TwitterScreenName='BBCFergusWalsh', TwitterUserID='146513211', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Fiona Trott', TwitterScreenName='bbcfionatrott', TwitterUserID='145163960', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Gavin Hewitt', TwitterScreenName='BBCGavinHewitt', TwitterUserID='52000483', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Hugh Pym', TwitterScreenName='BBCHughPym', TwitterUserID='157044469', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='James Cook', TwitterScreenName='BBCJamesCook', TwitterUserID='17024780', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='James Landale', TwitterScreenName='BBCjlandale', TwitterUserID='166712218', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Jon Sopel', TwitterScreenName='BBCJonSopel', TwitterUserID='130104942', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Karen Allen', TwitterScreenName='BBCKarenAllen', TwitterUserID='205257492', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Karin Giannone', TwitterScreenName='BBCKarinG', TwitterUserID='192318065', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Kasra Naji', TwitterScreenName='BBCKasraNaji', TwitterUserID='322810914', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Kim Ghattas', TwitterScreenName='BBCKimGhattas', TwitterUserID='44638576', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Komla Dumor', TwitterScreenName='bbckomladumor', TwitterUserID='47069130', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='lawrence mann', TwitterScreenName='BBCLawrence', TwitterUserID='138385877', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Lerato Mbele', TwitterScreenName='BBCLerato', TwitterUserID='620186949', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Lina Sinjab', TwitterScreenName='BBCLinaSinjab', TwitterUserID='164827760', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Louise Stewart', TwitterScreenName='BBCLouise', TwitterUserID='275024798', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='lyse doucet', TwitterScreenName='BBCLyseDoucet', TwitterUserID='108352527', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Mark Denten', TwitterScreenName='BBCMarkDenten', TwitterUserID='78384612', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Mark Easton', TwitterScreenName='BBCMarkEaston', TwitterUserID='263160998', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Mark Mardell', TwitterScreenName='BBCMarkMardell', TwitterUserID='69860260', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Mark Simpson', TwitterScreenName='BBCMarkSimpson', TwitterUserID='296319355', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Mike Embley', TwitterScreenName='BBCMikeEmbley', TwitterUserID='27617013', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Naga Munchetty', TwitterScreenName='BBCNaga', TwitterUserID='262672654', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='BBC Newsnight', TwitterScreenName='BBCNewsnight', TwitterUserID='20543416', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Nick Robinson', TwitterScreenName='bbcnickrobinson', TwitterUserID='25984418', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Nik Gowing', TwitterScreenName='BBCNikGowing', TwitterUserID='19281401', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='norman smith', TwitterScreenName='BBCNormanS', TwitterUserID='106118793', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Nuala McGovern', TwitterScreenName='BBCNuala', TwitterUserID='624579080', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Pallab Ghosh', TwitterScreenName='BBCPallab', TwitterUserID='329600057', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Paul Adams', TwitterScreenName='BBCPaulAdams', TwitterUserID='103729162', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Peter Henley', TwitterScreenName='BBCPeterH', TwitterUserID='25273713', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Peter Hunt', TwitterScreenName='BBCPeterHunt', TwitterUserID='243630696', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='BBC Question Time', TwitterScreenName='bbcquestiontime', TwitterUserID='20699709', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='BBC Radio 4 Today', TwitterScreenName='BBCR4Today', TwitterUserID='8170292', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Raymond Buchanan', TwitterScreenName='BBCRaymondB', TwitterUserID='125820691', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Richard Black', TwitterScreenName='BBCRBlack', TwitterUserID='95428712', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Richard Moss', TwitterScreenName='BBCRichardMoss', TwitterUserID='34274845', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Robin Lustig', TwitterScreenName='bbcrobinlustig', TwitterUserID='256248787', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Rory Cellan-Jones', TwitterScreenName='BBCRoryCJ', TwitterUserID='104615636', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Ros Atkins', TwitterScreenName='BBCRosAtkins', TwitterUserID='92771309', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Sanjoy Majumder', TwitterScreenName='BBCSanjoyM', TwitterUserID='127790650', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='David Ornstein', TwitterScreenName='bbcsport_david', TwitterUserID='46875124', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Ollie Williams', TwitterScreenName='BBCSport_Ollie', TwitterUserID='14747297', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Stephanie Flanders', TwitterScreenName='BBCStephanie', TwitterUserID='259288589', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Steve Rosenberg', TwitterScreenName='bbcstever', TwitterUserID='438111039', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Tanya Beckett', TwitterScreenName='BBCTanyaBeckett', TwitterUserID='19294743', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Thomas McGuigan', TwitterScreenName='BBCthomasmcg', TwitterUserID='184797801', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Tim Franks', TwitterScreenName='BBCTimFranks', TwitterUserID='117047389', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Tim Whewell', TwitterScreenName='BBCTimWhewell', TwitterUserID='250651231', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Tim Willcox', TwitterScreenName='BBCTimWillcox', TwitterUserID='197401382', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Tom Edwards', TwitterScreenName='BBCTomEdwards', TwitterUserID='179554859', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Torin Douglas', TwitterScreenName='BBCTorinD', TwitterUserID='41351472', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Zeinab Badawi', TwitterScreenName='bbczeinabbadawi', TwitterUserID='115430599', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Jonathan Beale', TwitterScreenName='bealejonathan', TwitterUserID='242354037', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Ben Ando', TwitterScreenName='benando', TwitterUserID='20223961', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Ben Mundy', TwitterScreenName='benmundy', TwitterUserID='133783256', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Ben Smith', TwitterScreenName='BenSmithBBC', TwitterUserID='125148375', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Bill Turnbull', TwitterScreenName='billtu', TwitterUserID='17716950', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Gary O''Donoghue', TwitterScreenName='BlindGazza', TwitterUserID='56565843', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='branwen jeffreys', TwitterScreenName='branwenjeffreys', TwitterUserID='224592767', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Bilal Sarwary', TwitterScreenName='bsarwary', TwitterUserID='162171805', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='michael cairns', TwitterScreenName='Cairnspolitics', TwitterUserID='271423566', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Carole Walker', TwitterScreenName='carolewalkercw', TwitterUserID='332921290', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Caroline Hawley', TwitterScreenName='carolinehawley', TwitterUserID='93155353', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Caroline Wyatt', TwitterScreenName='carolinewyatt', TwitterUserID='37258354', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Charles Haviland', TwitterScreenName='cfhaviland', TwitterUserID='69920973', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Chris Mason', TwitterScreenName='ChrisMasonBBC', TwitterUserID='22460658', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='clive coleman', TwitterScreenName='colemancr', TwitterUserID='233918058', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Colin Paterson', TwitterScreenName='ColinGPaterson', TwitterUserID='20011071', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Sean Curran', TwitterScreenName='cripeswatson', TwitterUserID='226542784', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Cara Swift', TwitterScreenName='cswift2', TwitterUserID='161627772', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Danny Savage', TwitterScreenName='dannysavage', TwitterUserID='114774299', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Danny Shaw', TwitterScreenName='DannyShawBBC', TwitterUserID='209584092', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Dan Whitworth', TwitterScreenName='danwtech', TwitterUserID='155529304', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Dave Lee', TwitterScreenName='davelee', TwitterUserID='4229391', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Damian Grammaticas', TwitterScreenName='dngbbc', TwitterUserID='218770932', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Mark Doyle', TwitterScreenName='Doylebytes', TwitterUserID='111319219', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Gary Duffy', TwitterScreenName='Duffygary', TwitterUserID='108964710', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Ed Thomas', TwitterScreenName='EdThomas76', TwitterUserID='50079244', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Emily Buchanan', TwitterScreenName='EmilyBuchanan1', TwitterUserID='258748529', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Evan Davis', TwitterScreenName='EvanHD', TwitterUserID='19530134', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Fergal Keane', TwitterScreenName='fergalkeane47', TwitterUserID='265398605', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Christian Fraser', TwitterScreenName='ForeignCorresp', TwitterUserID='250780210', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Gavin Esler', TwitterScreenName='gavinesler', TwitterUserID='174292801', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Gavin Lee', TwitterScreenName='GavinLeeBBC', TwitterUserID='18632368', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Gabriel Gatehouse', TwitterScreenName='ggatehouse', TwitterUserID='257367223', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Simon Gompertz BBC', TwitterScreenName='gompertz', TwitterUserID='18983132', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Gordon Corera', TwitterScreenName='gordoncorera', TwitterUserID='242355547', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Jamie Angus', TwitterScreenName='grvlx001', TwitterUserID='17720465', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Guy Smith', TwitterScreenName='GuySmithReports', TwitterUserID='78655835', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='helena merriman', TwitterScreenName='helenamerriman', TwitterUserID='31381041', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Nick Higham', TwitterScreenName='highamnews', TwitterUserID='68378203', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Hywel Griffith', TwitterScreenName='hywel_griffith', TwitterUserID='304405388', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='iain watson', TwitterScreenName='iainjwatson', TwitterUserID='116845797', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Imogen Foulkes', TwitterScreenName='ImogenFoulkes', TwitterUserID='581740562', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='James Copnall', TwitterScreenName='JamesCopnall', TwitterUserID='401520924', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='James Reynolds', TwitterScreenName='JamesEReynolds', TwitterUserID='66802285', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='James Buchanan', TwitterScreenName='JamesWBuchanan', TwitterUserID='19538322', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Jane Dreaper', TwitterScreenName='janedreaper', TwitterUserID='29719911', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Jane Hill', TwitterScreenName='JaneHillNews', TwitterUserID='129143625', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Jeremy Britton', TwitterScreenName='jeremy_britton1', TwitterUserID='380830009', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Jill McGivering', TwitterScreenName='jmcgivering', TwitterUserID='130958772', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Joanna Carr', TwitterScreenName='jocarr', TwitterUserID='19538776', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Jo', TwitterScreenName='JoFloto', TwitterUserID='47618776', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='John Moylan', TwitterScreenName='JohnMoylanBiz', TwitterUserID='235973288', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Jonah Fisher', TwitterScreenName='JonahFisher', TwitterUserID='23052625', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Jon Manel', TwitterScreenName='jonmanel', TwitterUserID='192256832', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Jonny Hallam', TwitterScreenName='Jonny_Hallam', TwitterUserID='19910285', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Jonny Dymond', TwitterScreenName='jonnydymond', TwitterUserID='18490963', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Jonty Bloom', TwitterScreenName='JontyBloombiz', TwitterUserID='269801196', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Joseph Winter', TwitterScreenName='JosephWinter', TwitterUserID='329555005', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Judith Moritz', TwitterScreenName='JudithMoritz', TwitterUserID='361881520', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='justin webb', TwitterScreenName='JustinOnWeb', TwitterUserID='179887262', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Karishma Vaswani', TwitterScreenName='Karishma7', TwitterUserID='18983292', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Katty Kay', TwitterScreenName='KattyKayBBC', TwitterUserID='43996908', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='katya adler', TwitterScreenName='katyaadler', TwitterUserID='393637870', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Duncan Kennedy', TwitterScreenName='kenned10', TwitterUserID='21083529', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Kevin Bakhurst', TwitterScreenName='kevinbakhurst', TwitterUserID='19526770', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Kirsty Gardner', TwitterScreenName='KirstyGardner', TwitterUserID='19976446', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Lars Bevanger', TwitterScreenName='lbevanger', TwitterUserID='19901224', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Lesley Ashmall', TwitterScreenName='lesleyashmall', TwitterUserID='304321569', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Louise Hubball', TwitterScreenName='LouiseHubball', TwitterUserID='246348645', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Lucy Walker', TwitterScreenName='LucyNews', TwitterUserID='31090570', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Lucy Williamson', TwitterScreenName='lucywilliamson', TwitterUserID='20498140', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Luisa Baldini', TwitterScreenName='LuisaBaldini1', TwitterUserID='295095161', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Mohamed Madi', TwitterScreenName='m_madi', TwitterUserID='48555703', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='emily m', TwitterScreenName='maitlis', TwitterUserID='20631422', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Marc Ashdown', TwitterScreenName='marcashdown', TwitterUserID='112447678', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Mark Daly', TwitterScreenName='markdaly2', TwitterUserID='256959080', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Mark Hutchings', TwitterScreenName='markhutchings1', TwitterUserID='262122071', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Mark Lowen', TwitterScreenName='marklowen', TwitterUserID='230014404', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Marko Zoric', TwitterScreenName='MarkoZoricJurno', TwitterUserID='22757873', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Claire Marshall', TwitterScreenName='marshallwords', TwitterUserID='393304554', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Martha Kearney', TwitterScreenName='Marthakearney', TwitterUserID='118626543', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Martin Patience', TwitterScreenName='martinpatience', TwitterUserID='258213767', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Mary Harper', TwitterScreenName='mary_harper', TwitterUserID='44657518', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Matt Precey', TwitterScreenName='mattcprecey', TwitterUserID='21670557', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Matt Danzico', TwitterScreenName='mattdanzico', TwitterUserID='5690002', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Matthew Price', TwitterScreenName='matthewwprice', TwitterUserID='47646874', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='matt prodger', TwitterScreenName='mattprodger', TwitterUserID='92514626', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Mike Henson', TwitterScreenName='MikeHensonBBC', TwitterUserID='278071536', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Mishal Husain', TwitterScreenName='MishalHusainBBC', TwitterUserID='74265849', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='James Naughtie', TwitterScreenName='naughtiej', TwitterUserID='60845623', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Nick Hope', TwitterScreenName='NickHopeBBC', TwitterUserID='121627048', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Andrew North', TwitterScreenName='NorthAndrew', TwitterUserID='245208137', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Owen Bennett Jones', TwitterScreenName='OwenBennettJone', TwitterUserID='320971248', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Patrick Burns', TwitterScreenName='PatrickBurnsBBC', TwitterUserID='400030803', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Paul Danahar', TwitterScreenName='pdanahar', TwitterUserID='311989458', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Kevin Peachey', TwitterScreenName='PeacheyK', TwitterUserID='140808864', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Robert Peston', TwitterScreenName='peston', TwitterUserID='14157134', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Peter Biles', TwitterScreenName='peterbiles', TwitterUserID='156617262', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Peter Bowes', TwitterScreenName='peterbowes', TwitterUserID='8771162', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Peter Leng', TwitterScreenName='PeterLeng', TwitterUserID='110951035', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Philippa Thomas', TwitterScreenName='PhilippaNews', TwitterUserID='49492585', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Phil Mackie', TwitterScreenName='philmackie', TwitterUserID='20671307', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Phil McNulty', TwitterScreenName='philmcnulty', TwitterUserID='46343990', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Rachel Thompson', TwitterScreenName='raeontheroad', TwitterUserID='19395898', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Rajini Vaidyanathan', TwitterScreenName='rajiniv', TwitterUserID='240879503', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Rana Jawad', TwitterScreenName='Rana_J01', TwitterUserID='430752604', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='rayhan demytrie', TwitterScreenName='rayhandemytrie', TwitterUserID='438168212', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Richard Burgess', TwitterScreenName='rburgessbbc', TwitterUserID='147732420', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Reeta Chakrabarti', TwitterScreenName='rchak100', TwitterUserID='92776929', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Richard Colebourn', TwitterScreenName='rcolebourn', TwitterUserID='172734849', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Richard Conway BBC', TwitterScreenName='richard_conway', TwitterUserID='16241871', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Richard Galpin', TwitterScreenName='Richardgalpin', TwitterUserID='23294872', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Richard Westcott', TwitterScreenName='richardwestcott', TwitterUserID='154226261', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Robert Hall', TwitterScreenName='RobertHall61', TwitterUserID='59029274', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='robinbrant', TwitterScreenName='robinbrant', TwitterUserID='15355411', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Roland Buerk', TwitterScreenName='roland_buerk', TwitterUserID='27856377', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Martin Rosenbaum', TwitterScreenName='rosenbaum6', TwitterUserID='20132289', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Rushdi Abualouf', TwitterScreenName='Rushdibbc', TwitterUserID='136776767', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Sam Naz', TwitterScreenName='SamNazBBC', TwitterUserID='233651490', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Sanchia Berg', TwitterScreenName='Sanchia7', TwitterUserID='21655680', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Sarah Montague', TwitterScreenName='Sarah_Montague', TwitterUserID='249565463', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Sarah Ransome', TwitterScreenName='Sarah_Ransome', TwitterUserID='49944701', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='sarah campbell', TwitterScreenName='SarahCam3', TwitterUserID='51820472', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Sarah Grainger', TwitterScreenName='sarahgrainger', TwitterUserID='40075059', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Sean Coughlan', TwitterScreenName='seanjcoughlan', TwitterUserID='274620149', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Shahzeb Jillani', TwitterScreenName='ShahzebJillani', TwitterUserID='100215373', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Shelagh Fogarty', TwitterScreenName='ShelaghFogarty', TwitterUserID='96092282', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Sian Williams', TwitterScreenName='sianwilliams100', TwitterUserID='145173210', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Simon Dedman', TwitterScreenName='SiDedman', TwitterUserID='40370254', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='simon wilson', TwitterScreenName='siwilso', TwitterUserID='45996631', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='sophieraworth', TwitterScreenName='sophieraworth', TwitterUserID='99560384', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='soutik biswas', TwitterScreenName='soutik', TwitterUserID='21565678', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Stephen Smith', TwitterScreenName='StephenSmithBBC', TwitterUserID='507513268', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='stephen mawhinney', TwitterScreenName='steve_mawhinney', TwitterUserID='73080210', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='steve swann', TwitterScreenName='steveswannBBC', TwitterUserID='216659406', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Stuart Hughes', TwitterScreenName='stuartdhughes', TwitterUserID='145189980', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Su Maskell', TwitterScreenName='SuMaskell', TwitterUserID='210747536', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='David Willis', TwitterScreenName='THEDavidWillis', TwitterUserID='77941254', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Tim Muffett', TwitterScreenName='timmuffett', TwitterUserID='20139326', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Tim Reid', TwitterScreenName='TimReidBBC', TwitterUserID='42866071', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Tim Smith', TwitterScreenName='timsmithyorks', TwitterUserID='100844081', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Tim Masters', TwitterScreenName='timtardis', TwitterUserID='15235679', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Len Tingle', TwitterScreenName='Tinglepolitics', TwitterUserID='229823197', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Toby Mason', TwitterScreenName='TobyMasonBBC', TwitterUserID='466660174', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Tom Burridge', TwitterScreenName='TomBurridgebbc', TwitterUserID='242985834', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Tom Feilden', TwitterScreenName='TomFeilden', TwitterUserID='132523809', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='tomsymonds', TwitterScreenName='tomsymonds', TwitterUserID='8242572', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Tony Smith', TwitterScreenName='TonyNewsCamera', TwitterUserID='242366566', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Victoria Derbyshire', TwitterScreenName='vicderbyshire', TwitterUserID='19964034', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='vivek raj', TwitterScreenName='vivekrajindia', TwitterUserID='258684352', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Viv Marsh', TwitterScreenName='vivmarshuk', TwitterUserID='102738131', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='WaheedMassoud', TwitterScreenName='WaheedMassoud', TwitterUserID='337684167', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='wietske burema', TwitterScreenName='wburema', TwitterUserID='41126466', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Will Grant', TwitterScreenName='will__grant', TwitterUserID='105370495', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Jon Williams', TwitterScreenName='williamsjon', TwitterUserID='14460241', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='will ross', TwitterScreenName='willintune', TwitterUserID='219369725', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Mark Worthington', TwitterScreenName='worthingtonmark', TwitterUserID='342006160', Processed=0
insert into [dbo].[AtheletesDetails] select ProfileUID='', Name='Zubeida Malik', TwitterScreenName='zubeidamalik', TwitterUserID='142644573', Processed=0

