//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBC.Dna.Api.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("server=ops-dbdev1.national.core.bbc.co.uk; port=3312; user id=profile; password=c" +
            "rudmeister; database=mdb; pooling=true")]
        public string ProfileRead {
            get {
                return ((string)(this["ProfileRead"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("server=ops-dbdev1.national.core.bbc.co.uk; port=3312; user id=profile; password=c" +
            "rudmeister; database=mdb; pooling=true")]
        public string ProfileWrite {
            get {
                return ((string)(this["ProfileWrite"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.stage.bbc.co.uk/opensso/identityservices/IdentityServices;dna live;10" +
            ".152.4.15:80;logging")]
        public string Identity {
            get {
                return ((string)(this["Identity"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=TheGuide;Integrated Security=True;MultipleActiveRes" +
            "ultSets=True")]
        public string DNADataBase {
            get {
                return ((string)(this["DNADataBase"]));
            }
        }
    }
}
