#ifndef PROFILESQL_H
#define PROFILESQL_H


class CProfileSql
{	
	friend class CProfileApi;
	friend class CProfileApiBase;
	friend class CProfileApiContext;

	static const char* m_sSqlSelKeys;
	static const char* m_sSqlSelAdmKeys;
	static const char* m_sSqlSelUsersStatusProfile;
	static const char* m_sSqlSelUsersRangeStatusProfile;
	static const char* m_sSqlSelUsersStatusOnly;
	static const char* m_sSqlSelUsersRangeStatusOnly;
	static const char* m_sSqlSelUsers;
	static const char* m_sSqlSelUsersRange;
	static const char* m_sSqlSelUsersProfileOnly;
	static const char* m_sSqlSelUsersRangeProfileOnly;
	static const char* m_sSqlSelUnusedAttributes;
	static const char* m_sSqlSelAttributeServices;
	static const char* m_sSqlInsServiceAttribute;
	static const char* m_sSqlDelServiceAttribute;
	static const char* m_sSqlUpdServiceAttribute;
	static const char* m_sSqlInsAttribute;
	static const char* m_sSqlSelAttribute;
	static const char* m_sSqlSelAttributes;
	static const char* m_sSqlUpdAttribute;
	static const char* m_sSqlDelAttribute;
	static const char* m_sSqlDelServiceAttributeAll;
	static const char* m_sSqlSetUserType;
	static const char* m_sSqlUpdService;
	static const char* m_sSqlInsServices;
	static const char* m_sSqlSelServices;
	static const char* m_sSqlSelService;
	static const char* m_sSqlSelUserIdUsername;
	static const char* m_sSqlSetMustChangePassword;
	static const char* m_sSqlSelMustChangePassword;
	static const char* m_sSqlInsUserEvent;
	static const char* m_sSqlSelUserIdUsernameTaken;
	static const char* m_sSqlSelUserPassword;
	static const char* m_sSqlSelUserByName;
	static const char* m_sSqlSelUserByCudId;
	static const char* m_sSqlSelUserById;
	static const char* m_sSqlSelUserRegisteredService;
	static const char* m_sSqlSelAdminUsers;
	static const char* m_sSqlSelServiceByName;
	static const char* m_sSqlSelUserList;
	static const char* m_sSqlSelReverseUserList;
	static const char* m_sSqlSelCodes;
	static const char* m_sSqlSelCountries;
	static const char* m_sSqlSelCountry;
	static const char* m_sSqlSelCodeRefSpecific;
	static const char* m_sSqlSelUserServiceAdminMessagesBeforeLogin;
	static const char* m_sSqlSelUserServiceAdminMessagesAfterLogin;
	static const char* m_sSqlSelAdminMessages;
	static const char* m_sSqlDelAdminMessage;
	static const char* m_sSqlInsAdminMessage;
	static const char* m_sSqlSelUserRequest;
	static const char* m_sSqlSelUserRequestOwn;
	static const char* m_sSqlSelUserType;
	static const char* m_sSqlSelUserStatus;
	static const char* m_sSqlSelUserStatusByName;
	static const char* m_sSqlSelAdminLog;
	static const char* m_sSqlInsAdminLog;
	static const char* m_sSqlSelRegisteredUserService;
	static const char* m_sSqlSelAdminServices;
	static const char* m_sSqlSelUserAttInfo;	
	static const char* m_sSqlSelUserAttInfoSysCall;	
	static const char* m_sSqlSelAttInfo;
	static const char* m_sSqlSelAttributesInfo;
	static const char* m_sSqlSelUserProfile;
	static const char* m_sSqlSelOtherUserProfile;
	static const char* m_sSqlSelOtherUserProfileByName;
	static const char* m_sSqlSelOtherUserProfileSubsetByName;
	static const char* m_sSqlSelOtherUserProfileSubset;
	static const char* m_sSqlSelUserProfileSubset;
	static const char* m_sSqlSelUserProfileValue;
	static const char* m_sSqlSelUserProfileValueSysCall;
	static const char* m_sSqlLogoutFromAll;
	static const char* m_sSqlLogoutOnInvalidation;
	static const char* m_sSqlLogoutOnMandatoryMissing;
	static const char* m_sSqlSelMandatoryProfile;
	static const char* m_sSqlSelValidationProfile;
	static const char* m_sSqlSelBulkLogoutInfo;
	static const char* m_sSqlSelLoggedInUsersService;
	static const char* m_sSqlUpdUserServiceLogin;
	static const char* m_sSqlUpdUserServiceLogout;
	static const char* m_sSqlDelFromUserList;
	static const char* m_sSqlDelUserRequest;
	static const char* m_sSqlUpdUserRequestResponder;
	static const char* m_sSqlUpdUserProfileDate;
	static const char* m_sSqlUpdUserProfileInteger;
	static const char* m_sSqlUpdUserProfileDecimal;
	static const char* m_sSqlUpdUserProfileText;
	static const char* m_sSqlUpdAdminPassword;
	static const char* m_sSqlUpdUserPassword;
	static const char* m_sSqlUpdUserPasswordInvalidate;
	static const char* m_sSqlUpdUserName;
	static const char* m_sSqlUpdUserStatus;
	static const char* m_sSqlUpdUserAgreementAccepted;
	static const char* m_sSqlUpdUserServiceAgreementAccepted;
	static const char* m_sSqlUpdUserServiceAgreementAcceptedService;
	static const char* m_sSqlUpdUserServiceOnlineStatus;
	static const char* m_sSqlInsUser;
	static const char* m_sSqlInsUserService;
	static const char* m_sSqlUnregFromService;
	static const char* m_sSqlInsUserList;
	static const char* m_sSqlInsUserProfileDate;
	static const char* m_sSqlInsUserProfileInteger;
	static const char* m_sSqlInsUserProfileDecimal;
	static const char* m_sSqlInsUserProfileText;
	static const char* m_sSqlInsUserRequest;
	static const char* m_sSqlInsUserNameHistory;
	static const char* m_sSqlUpdScratchpad;
	static const char* m_sSqlInsScratchpad;
	static const char* m_sSqlSelScratchpad;
	static const char* m_sSqlSelDnaUser;
	static const char* m_sSqlSelCrypt;
	static const char* m_sSqlSelCudUserByName;
	static const char* m_sSqlSelCudUserByNameCudId;
	static const char* m_sSqlSelUsersByAttribute;
};

#endif
