#ifndef PROFILE_CODE_REF_H
#define PROFILE_CODE_REF_H

#define ADMIN_USER_TYPE			"ADMIN_USER_TYPE"
#define ADMIN_USER_TYPE_ADMIN	"ADMIN"
#define ADMIN_USER_TYPE_STAFF	"STAFF"

#define DATA_TYPE				"DATA_TYPE"
#define DATA_TYPE_BOOLEAN		"BOOLEAN"
#define DATA_TYPE_DATE			"DATE"
#define DATA_TYPE_DECIMAL		"DECIMAL"
#define DATA_TYPE_INTEGER		"INTEGER"
#define DATA_TYPE_TEXT			"TEXT"

#define ONLINE_STATUS				"ONLINE_STATUS"
#define ONLINE_STATUS_AVAILABLE		"AVAILABLE"
#define ONLINE_STATUS_AWAY			"AWAY"
#define ONLINE_STATUS_IDLE			"IDLE"
#define ONLINE_STATUS_OFFLINE		"OFFLINE"

#define USER_EVENT					"USER_EVENT"
#define USER_EVENT_CHANGEDET		"CHANGEDET"
#define USER_EVENT_CHANGEPASS		"CHANGEPASS"
#define USER_EVENT_CHANGEADMINPASS	"CHANGEADMPASS"
#define USER_EVENT_AUTOCHANGEPASS		"AUTOCHANGEPASS"
#define USER_EVENT_AUTOCHANGEADMINPASS	"AUTOCHANGEADMPASS"
#define USER_EVENT_LOGIN			"LOGIN"
#define USER_EVENT_LOGOUT			"LOGOUT"
#define USER_EVENT_BULK_LOGOUT		"BULKLOGOUT"
#define USER_EVENT_CHANGENAME		"CHANGENAME"
#define USER_EVENT_LOGOUTALL		"LOGOUTALL"
#define USER_EVENT_LOGOUTINVALID	"LOGOUTINV"
#define USER_EVENT_LOGOUTMANDATORY	"LOGOUTMAN"


#define USER_LIST_TYPE			"USER_LIST_TYPE"
#define USER_LIST_TYPE_BLOCK	"BLOCK"
#define USER_LIST_TYPE_BUDDY	"BUDDY"

#define USER_REQUEST			"USER_REQUEST"
#define USER_REQUEST_ADDCONTACT	"ADDCONTACT"

#define USER_RESPONSE			"USER_RESPONSE"
#define USER_RESPONSE_ACCEPT	"ACCEPT"
#define USER_RESPONSE_DENY		"DENY"

#define USER_STATUS				"USER_STATUS"
#define USER_STATUS_REMOVED		"REMOVED"
#define USER_STATUS_VALID		"VALID"

#define USER_TYPE			"USER_TYPE"
#define USER_TYPE_STAFF		"STAFF"
#define USER_TYPE_EXTERNAL	"EXTERNAL"
#define USER_TYPE_ADMIN		"ADMIN"

#define	MODERATION_STATUS	"MODERATION_STATUS"
#define	WARNING_BAN1		"BAN1"
#define	WARNING_BAN2		"BAN2"
#define	WARNING_BAN3		"BAN3"
#define	WARNING_NONE		"NONE"
#define	WARNING_TOTALBAN	"TOTALBAN"
#define	WARNING_WARN1		"WARN1"
#define	WARNING_WARN2		"WARN2"
#define	WARNING_WARN3		"WARN3"

#endif
