CREATE PROCEDURE removekeyarticles	@siteid int,
										@artname1 varchar(255) = NULL,
										@artname2 varchar(255) = NULL,										
										@artname3 varchar(255) = NULL,										
										@artname4 varchar(255) = NULL,
										@artname5 varchar(255) = NULL,
										@artname6 varchar(255) = NULL,
										@artname7 varchar(255) = NULL,
										@artname8 varchar(255) = NULL,
										@artname9 varchar(255) = NULL,
										@artname10 varchar(255) = NULL,
										@artname11 varchar(255) = NULL,
										@artname12 varchar(255) = NULL,
										@artname13 varchar(255) = NULL,
										@artname14 varchar(255) = NULL,
										@artname15 varchar(255) = NULL,
										@artname16 varchar(255) = NULL,
										@artname17 varchar(255) = NULL,
										@artname18 varchar(255) = NULL,
										@artname19 varchar(255) = NULL,
										@artname20 varchar(255) = NULL
As
DELETE FROM KeyArticles
	WHERE SiteID = @siteid
	AND ArticleName IN (	@artname1,
							@artname2,
							@artname3,
							@artname4,
							@artname5,
							@artname6,
							@artname7,
							@artname8,
							@artname9,
							@artname10,
							@artname11,
							@artname12,
							@artname13,
							@artname14,
							@artname15,
							@artname16,
							@artname17,
							@artname18,
							@artname19,
							@artname20)
