/*
exec AddAppOid 'DNA-RipleyServer','1.3.6.1.4.1.2333.3.2.144'
exec AddAppOid 'DNA-BBC.DNA','1.3.6.1.4.1.2333.3.2.148'
exec AddAppOid 'DNA-API-Comments','1.3.6.1.4.1.2333.3.2.149'
exec AddAppOid 'DNA-EventsService','1.3.6.1.4.1.2333.3.2.150'
*/
-------------------------------------- AverageRequestTime
exec AddKPIConfig 'DNA-RipleyServer', 'narthur1', 'AverageRequestTime','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-RipleyServer', 'narthur2', 'AverageRequestTime','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-RipleyServer', 'narthur3', 'AverageRequestTime','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-RipleyServer', 'narthur4', 'AverageRequestTime','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-RipleyServer', 'narthur8', 'AverageRequestTime','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-RipleyServer', 'narthur9', 'AverageRequestTime','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-RipleyServer', 'narthur10', 'AverageRequestTime','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-RipleyServer', 'narthur11', 'AverageRequestTime','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-RipleyServer', 'narthur12', 'AverageRequestTime','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-RipleyServer', 'narthur13', 'AverageRequestTime','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-RipleyServer', 'narthur14', 'AverageRequestTime','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-RipleyServer', 'narthur15', 'AverageRequestTime','GAUGE', 'http://www.bbc.co.uk','ms'

exec AddKPIConfig 'DNA-BBC.DNA', 'narthur1', 'AverageRequestTime','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-BBC.DNA', 'narthur2', 'AverageRequestTime','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-BBC.DNA', 'narthur3', 'AverageRequestTime','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-BBC.DNA', 'narthur4', 'AverageRequestTime','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-BBC.DNA', 'narthur8', 'AverageRequestTime','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-BBC.DNA', 'narthur9', 'AverageRequestTime','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-BBC.DNA', 'narthur10', 'AverageRequestTime','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-BBC.DNA', 'narthur11', 'AverageRequestTime','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-BBC.DNA', 'narthur12', 'AverageRequestTime','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-BBC.DNA', 'narthur13', 'AverageRequestTime','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-BBC.DNA', 'narthur14', 'AverageRequestTime','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-BBC.DNA', 'narthur15', 'AverageRequestTime','GAUGE', 'http://www.bbc.co.uk','ms'

exec AddKPIConfig 'DNA-API-Comments', 'narthur1', 'AverageRequestTime','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-API-Comments', 'narthur2', 'AverageRequestTime','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-API-Comments', 'narthur3', 'AverageRequestTime','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-API-Comments', 'narthur4', 'AverageRequestTime','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-API-Comments', 'narthur8', 'AverageRequestTime','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-API-Comments', 'narthur9', 'AverageRequestTime','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-API-Comments', 'narthur10', 'AverageRequestTime','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-API-Comments', 'narthur11', 'AverageRequestTime','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-API-Comments', 'narthur12', 'AverageRequestTime','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-API-Comments', 'narthur13', 'AverageRequestTime','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-API-Comments', 'narthur14', 'AverageRequestTime','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-API-Comments', 'narthur15', 'AverageRequestTime','GAUGE', 'http://www.bbc.co.uk','ms'

exec AddKPIConfig 'DNA-RipleyServer', 'narthur16', 'AverageRequestTime','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-RipleyServer', 'narthur17', 'AverageRequestTime','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-RipleyServer', 'narthur18', 'AverageRequestTime','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-RipleyServer', 'narthur19', 'AverageRequestTime','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-RipleyServer', 'narthur20', 'AverageRequestTime','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-RipleyServer', 'narthur21', 'AverageRequestTime','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-RipleyServer', 'narthur22', 'AverageRequestTime','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-RipleyServer', 'narthur23', 'AverageRequestTime','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-RipleyServer', 'narthur24', 'AverageRequestTime','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-RipleyServer', 'narthur25', 'AverageRequestTime','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-RipleyServer', 'narthur26', 'AverageRequestTime','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-RipleyServer', 'narthur27', 'AverageRequestTime','GAUGE', 'http://www.bbc.co.uk','ms'

exec AddKPIConfig 'DNA-BBC.DNA', 'narthur16', 'AverageRequestTime','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-BBC.DNA', 'narthur17', 'AverageRequestTime','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-BBC.DNA', 'narthur18', 'AverageRequestTime','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-BBC.DNA', 'narthur19', 'AverageRequestTime','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-BBC.DNA', 'narthur20', 'AverageRequestTime','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-BBC.DNA', 'narthur21', 'AverageRequestTime','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-BBC.DNA', 'narthur22', 'AverageRequestTime','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-BBC.DNA', 'narthur23', 'AverageRequestTime','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-BBC.DNA', 'narthur24', 'AverageRequestTime','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-BBC.DNA', 'narthur25', 'AverageRequestTime','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-BBC.DNA', 'narthur26', 'AverageRequestTime','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-BBC.DNA', 'narthur27', 'AverageRequestTime','GAUGE', 'http://www.bbc.co.uk','ms'

exec AddKPIConfig 'DNA-API-Comments', 'narthur16', 'AverageRequestTime','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-API-Comments', 'narthur17', 'AverageRequestTime','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-API-Comments', 'narthur18', 'AverageRequestTime','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-API-Comments', 'narthur19', 'AverageRequestTime','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-API-Comments', 'narthur20', 'AverageRequestTime','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-API-Comments', 'narthur21', 'AverageRequestTime','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-API-Comments', 'narthur22', 'AverageRequestTime','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-API-Comments', 'narthur23', 'AverageRequestTime','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-API-Comments', 'narthur24', 'AverageRequestTime','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-API-Comments', 'narthur25', 'AverageRequestTime','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-API-Comments', 'narthur26', 'AverageRequestTime','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-API-Comments', 'narthur27', 'AverageRequestTime','GAUGE', 'http://www.bbc.co.uk','ms'

-------------------------------------- ServerTooBusyCount
exec AddKPIConfig 'DNA-RipleyServer', 'narthur1', 'ServerTooBusyCount','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-RipleyServer', 'narthur2', 'ServerTooBusyCount','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-RipleyServer', 'narthur3', 'ServerTooBusyCount','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-RipleyServer', 'narthur4', 'ServerTooBusyCount','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-RipleyServer', 'narthur8', 'ServerTooBusyCount','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-RipleyServer', 'narthur9', 'ServerTooBusyCount','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-RipleyServer', 'narthur10', 'ServerTooBusyCount','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-RipleyServer', 'narthur11', 'ServerTooBusyCount','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-RipleyServer', 'narthur12', 'ServerTooBusyCount','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-RipleyServer', 'narthur13', 'ServerTooBusyCount','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-RipleyServer', 'narthur14', 'ServerTooBusyCount','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-RipleyServer', 'narthur15', 'ServerTooBusyCount','GAUGE', 'http://www.bbc.co.uk','ms'

exec AddKPIConfig 'DNA-BBC.DNA', 'narthur1', 'ServerTooBusyCount','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-BBC.DNA', 'narthur2', 'ServerTooBusyCount','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-BBC.DNA', 'narthur3', 'ServerTooBusyCount','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-BBC.DNA', 'narthur4', 'ServerTooBusyCount','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-BBC.DNA', 'narthur8', 'ServerTooBusyCount','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-BBC.DNA', 'narthur9', 'ServerTooBusyCount','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-BBC.DNA', 'narthur10', 'ServerTooBusyCount','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-BBC.DNA', 'narthur11', 'ServerTooBusyCount','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-BBC.DNA', 'narthur12', 'ServerTooBusyCount','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-BBC.DNA', 'narthur13', 'ServerTooBusyCount','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-BBC.DNA', 'narthur14', 'ServerTooBusyCount','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-BBC.DNA', 'narthur15', 'ServerTooBusyCount','GAUGE', 'http://www.bbc.co.uk','ms'

exec AddKPIConfig 'DNA-API-Comments', 'narthur1', 'ServerTooBusyCount','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-API-Comments', 'narthur2', 'ServerTooBusyCount','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-API-Comments', 'narthur3', 'ServerTooBusyCount','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-API-Comments', 'narthur4', 'ServerTooBusyCount','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-API-Comments', 'narthur8', 'ServerTooBusyCount','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-API-Comments', 'narthur9', 'ServerTooBusyCount','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-API-Comments', 'narthur10', 'ServerTooBusyCount','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-API-Comments', 'narthur11', 'ServerTooBusyCount','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-API-Comments', 'narthur12', 'ServerTooBusyCount','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-API-Comments', 'narthur13', 'ServerTooBusyCount','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-API-Comments', 'narthur14', 'ServerTooBusyCount','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-API-Comments', 'narthur15', 'ServerTooBusyCount','GAUGE', 'http://www.bbc.co.uk','ms'

exec AddKPIConfig 'DNA-RipleyServer', 'narthur16', 'ServerTooBusyCount','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-RipleyServer', 'narthur17', 'ServerTooBusyCount','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-RipleyServer', 'narthur18', 'ServerTooBusyCount','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-RipleyServer', 'narthur19', 'ServerTooBusyCount','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-RipleyServer', 'narthur20', 'ServerTooBusyCount','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-RipleyServer', 'narthur21', 'ServerTooBusyCount','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-RipleyServer', 'narthur22', 'ServerTooBusyCount','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-RipleyServer', 'narthur23', 'ServerTooBusyCount','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-RipleyServer', 'narthur24', 'ServerTooBusyCount','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-RipleyServer', 'narthur25', 'ServerTooBusyCount','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-RipleyServer', 'narthur26', 'ServerTooBusyCount','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-RipleyServer', 'narthur27', 'ServerTooBusyCount','GAUGE', 'http://www.bbc.co.uk','ms'

exec AddKPIConfig 'DNA-BBC.DNA', 'narthur16', 'ServerTooBusyCount','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-BBC.DNA', 'narthur17', 'ServerTooBusyCount','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-BBC.DNA', 'narthur18', 'ServerTooBusyCount','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-BBC.DNA', 'narthur19', 'ServerTooBusyCount','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-BBC.DNA', 'narthur20', 'ServerTooBusyCount','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-BBC.DNA', 'narthur21', 'ServerTooBusyCount','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-BBC.DNA', 'narthur22', 'ServerTooBusyCount','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-BBC.DNA', 'narthur23', 'ServerTooBusyCount','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-BBC.DNA', 'narthur24', 'ServerTooBusyCount','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-BBC.DNA', 'narthur25', 'ServerTooBusyCount','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-BBC.DNA', 'narthur26', 'ServerTooBusyCount','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-BBC.DNA', 'narthur27', 'ServerTooBusyCount','GAUGE', 'http://www.bbc.co.uk','ms'

exec AddKPIConfig 'DNA-API-Comments', 'narthur16', 'ServerTooBusyCount','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-API-Comments', 'narthur17', 'ServerTooBusyCount','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-API-Comments', 'narthur18', 'ServerTooBusyCount','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-API-Comments', 'narthur19', 'ServerTooBusyCount','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-API-Comments', 'narthur20', 'ServerTooBusyCount','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-API-Comments', 'narthur21', 'ServerTooBusyCount','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-API-Comments', 'narthur22', 'ServerTooBusyCount','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-API-Comments', 'narthur23', 'ServerTooBusyCount','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-API-Comments', 'narthur24', 'ServerTooBusyCount','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-API-Comments', 'narthur25', 'ServerTooBusyCount','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-API-Comments', 'narthur26', 'ServerTooBusyCount','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-API-Comments', 'narthur27', 'ServerTooBusyCount','GAUGE', 'http://www.bbc.co.uk','ms'

-------------------------------------- RawRequests
exec AddKPIConfig 'DNA-RipleyServer', 'narthur1', 'RawRequests','DERIVE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-RipleyServer', 'narthur2', 'RawRequests','DERIVE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-RipleyServer', 'narthur3', 'RawRequests','DERIVE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-RipleyServer', 'narthur4', 'RawRequests','DERIVE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-RipleyServer', 'narthur8', 'RawRequests','DERIVE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-RipleyServer', 'narthur9', 'RawRequests','DERIVE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-RipleyServer', 'narthur10', 'RawRequests','DERIVE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-RipleyServer', 'narthur11', 'RawRequests','DERIVE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-RipleyServer', 'narthur12', 'RawRequests','DERIVE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-RipleyServer', 'narthur13', 'RawRequests','DERIVE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-RipleyServer', 'narthur14', 'RawRequests','DERIVE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-RipleyServer', 'narthur15', 'RawRequests','DERIVE', 'http://www.bbc.co.uk','ms'

exec AddKPIConfig 'DNA-BBC.DNA', 'narthur1', 'RawRequests','DERIVE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-BBC.DNA', 'narthur2', 'RawRequests','DERIVE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-BBC.DNA', 'narthur3', 'RawRequests','DERIVE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-BBC.DNA', 'narthur4', 'RawRequests','DERIVE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-BBC.DNA', 'narthur8', 'RawRequests','DERIVE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-BBC.DNA', 'narthur9', 'RawRequests','DERIVE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-BBC.DNA', 'narthur10', 'RawRequests','DERIVE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-BBC.DNA', 'narthur11', 'RawRequests','DERIVE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-BBC.DNA', 'narthur12', 'RawRequests','DERIVE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-BBC.DNA', 'narthur13', 'RawRequests','DERIVE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-BBC.DNA', 'narthur14', 'RawRequests','DERIVE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-BBC.DNA', 'narthur15', 'RawRequests','DERIVE', 'http://www.bbc.co.uk','ms'

exec AddKPIConfig 'DNA-API-Comments', 'narthur1', 'RawRequests','DERIVE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-API-Comments', 'narthur2', 'RawRequests','DERIVE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-API-Comments', 'narthur3', 'RawRequests','DERIVE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-API-Comments', 'narthur4', 'RawRequests','DERIVE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-API-Comments', 'narthur8', 'RawRequests','DERIVE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-API-Comments', 'narthur9', 'RawRequests','DERIVE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-API-Comments', 'narthur10', 'RawRequests','DERIVE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-API-Comments', 'narthur11', 'RawRequests','DERIVE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-API-Comments', 'narthur12', 'RawRequests','DERIVE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-API-Comments', 'narthur13', 'RawRequests','DERIVE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-API-Comments', 'narthur14', 'RawRequests','DERIVE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-API-Comments', 'narthur15', 'RawRequests','DERIVE', 'http://www.bbc.co.uk','ms'

exec AddKPIConfig 'DNA-RipleyServer', 'narthur16', 'RawRequests','DERIVE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-RipleyServer', 'narthur17', 'RawRequests','DERIVE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-RipleyServer', 'narthur18', 'RawRequests','DERIVE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-RipleyServer', 'narthur19', 'RawRequests','DERIVE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-RipleyServer', 'narthur20', 'RawRequests','DERIVE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-RipleyServer', 'narthur21', 'RawRequests','DERIVE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-RipleyServer', 'narthur22', 'RawRequests','DERIVE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-RipleyServer', 'narthur23', 'RawRequests','DERIVE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-RipleyServer', 'narthur24', 'RawRequests','DERIVE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-RipleyServer', 'narthur25', 'RawRequests','DERIVE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-RipleyServer', 'narthur26', 'RawRequests','DERIVE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-RipleyServer', 'narthur27', 'RawRequests','DERIVE', 'http://www.bbc.co.uk','ms'

exec AddKPIConfig 'DNA-BBC.DNA', 'narthur16', 'RawRequests','DERIVE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-BBC.DNA', 'narthur17', 'RawRequests','DERIVE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-BBC.DNA', 'narthur18', 'RawRequests','DERIVE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-BBC.DNA', 'narthur19', 'RawRequests','DERIVE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-BBC.DNA', 'narthur20', 'RawRequests','DERIVE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-BBC.DNA', 'narthur21', 'RawRequests','DERIVE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-BBC.DNA', 'narthur22', 'RawRequests','DERIVE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-BBC.DNA', 'narthur23', 'RawRequests','DERIVE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-BBC.DNA', 'narthur24', 'RawRequests','DERIVE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-BBC.DNA', 'narthur25', 'RawRequests','DERIVE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-BBC.DNA', 'narthur26', 'RawRequests','DERIVE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-BBC.DNA', 'narthur27', 'RawRequests','DERIVE', 'http://www.bbc.co.uk','ms'

exec AddKPIConfig 'DNA-API-Comments', 'narthur16', 'RawRequests','DERIVE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-API-Comments', 'narthur17', 'RawRequests','DERIVE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-API-Comments', 'narthur18', 'RawRequests','DERIVE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-API-Comments', 'narthur19', 'RawRequests','DERIVE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-API-Comments', 'narthur20', 'RawRequests','DERIVE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-API-Comments', 'narthur21', 'RawRequests','DERIVE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-API-Comments', 'narthur22', 'RawRequests','DERIVE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-API-Comments', 'narthur23', 'RawRequests','DERIVE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-API-Comments', 'narthur24', 'RawRequests','DERIVE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-API-Comments', 'narthur25', 'RawRequests','DERIVE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-API-Comments', 'narthur26', 'RawRequests','DERIVE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-API-Comments', 'narthur27', 'RawRequests','DERIVE', 'http://www.bbc.co.uk','ms'

-------------------------------------- ServerTooBusyPct
exec AddKPIConfig 'DNA-RipleyServer', 'narthur1', 'ServerTooBusyPct','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-RipleyServer', 'narthur2', 'ServerTooBusyPct','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-RipleyServer', 'narthur3', 'ServerTooBusyPct','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-RipleyServer', 'narthur4', 'ServerTooBusyPct','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-RipleyServer', 'narthur8', 'ServerTooBusyPct','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-RipleyServer', 'narthur9', 'ServerTooBusyPct','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-RipleyServer', 'narthur10', 'ServerTooBusyPct','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-RipleyServer', 'narthur11', 'ServerTooBusyPct','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-RipleyServer', 'narthur12', 'ServerTooBusyPct','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-RipleyServer', 'narthur13', 'ServerTooBusyPct','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-RipleyServer', 'narthur14', 'ServerTooBusyPct','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-RipleyServer', 'narthur15', 'ServerTooBusyPct','GAUGE', 'http://www.bbc.co.uk','ms'

exec AddKPIConfig 'DNA-BBC.DNA', 'narthur1', 'ServerTooBusyPct','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-BBC.DNA', 'narthur2', 'ServerTooBusyPct','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-BBC.DNA', 'narthur3', 'ServerTooBusyPct','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-BBC.DNA', 'narthur4', 'ServerTooBusyPct','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-BBC.DNA', 'narthur8', 'ServerTooBusyPct','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-BBC.DNA', 'narthur9', 'ServerTooBusyPct','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-BBC.DNA', 'narthur10', 'ServerTooBusyPct','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-BBC.DNA', 'narthur11', 'ServerTooBusyPct','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-BBC.DNA', 'narthur12', 'ServerTooBusyPct','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-BBC.DNA', 'narthur13', 'ServerTooBusyPct','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-BBC.DNA', 'narthur14', 'ServerTooBusyPct','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-BBC.DNA', 'narthur15', 'ServerTooBusyPct','GAUGE', 'http://www.bbc.co.uk','ms'

exec AddKPIConfig 'DNA-API-Comments', 'narthur1', 'ServerTooBusyPct','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-API-Comments', 'narthur2', 'ServerTooBusyPct','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-API-Comments', 'narthur3', 'ServerTooBusyPct','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-API-Comments', 'narthur4', 'ServerTooBusyPct','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-API-Comments', 'narthur8', 'ServerTooBusyPct','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-API-Comments', 'narthur9', 'ServerTooBusyPct','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-API-Comments', 'narthur10', 'ServerTooBusyPct','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-API-Comments', 'narthur11', 'ServerTooBusyPct','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-API-Comments', 'narthur12', 'ServerTooBusyPct','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-API-Comments', 'narthur13', 'ServerTooBusyPct','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-API-Comments', 'narthur14', 'ServerTooBusyPct','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-API-Comments', 'narthur15', 'ServerTooBusyPct','GAUGE', 'http://www.bbc.co.uk','ms'

exec AddKPIConfig 'DNA-RipleyServer', 'narthur16', 'ServerTooBusyPct','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-RipleyServer', 'narthur17', 'ServerTooBusyPct','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-RipleyServer', 'narthur18', 'ServerTooBusyPct','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-RipleyServer', 'narthur19', 'ServerTooBusyPct','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-RipleyServer', 'narthur20', 'ServerTooBusyPct','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-RipleyServer', 'narthur21', 'ServerTooBusyPct','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-RipleyServer', 'narthur22', 'ServerTooBusyPct','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-RipleyServer', 'narthur23', 'ServerTooBusyPct','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-RipleyServer', 'narthur24', 'ServerTooBusyPct','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-RipleyServer', 'narthur25', 'ServerTooBusyPct','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-RipleyServer', 'narthur26', 'ServerTooBusyPct','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-RipleyServer', 'narthur27', 'ServerTooBusyPct','GAUGE', 'http://www.bbc.co.uk','ms'

exec AddKPIConfig 'DNA-BBC.DNA', 'narthur16', 'ServerTooBusyPct','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-BBC.DNA', 'narthur17', 'ServerTooBusyPct','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-BBC.DNA', 'narthur18', 'ServerTooBusyPct','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-BBC.DNA', 'narthur19', 'ServerTooBusyPct','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-BBC.DNA', 'narthur20', 'ServerTooBusyPct','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-BBC.DNA', 'narthur21', 'ServerTooBusyPct','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-BBC.DNA', 'narthur22', 'ServerTooBusyPct','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-BBC.DNA', 'narthur23', 'ServerTooBusyPct','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-BBC.DNA', 'narthur24', 'ServerTooBusyPct','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-BBC.DNA', 'narthur25', 'ServerTooBusyPct','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-BBC.DNA', 'narthur26', 'ServerTooBusyPct','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-BBC.DNA', 'narthur27', 'ServerTooBusyPct','GAUGE', 'http://www.bbc.co.uk','ms'

exec AddKPIConfig 'DNA-API-Comments', 'narthur16', 'ServerTooBusyPct','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-API-Comments', 'narthur17', 'ServerTooBusyPct','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-API-Comments', 'narthur18', 'ServerTooBusyPct','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-API-Comments', 'narthur19', 'ServerTooBusyPct','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-API-Comments', 'narthur20', 'ServerTooBusyPct','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-API-Comments', 'narthur21', 'ServerTooBusyPct','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-API-Comments', 'narthur22', 'ServerTooBusyPct','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-API-Comments', 'narthur23', 'ServerTooBusyPct','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-API-Comments', 'narthur24', 'ServerTooBusyPct','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-API-Comments', 'narthur25', 'ServerTooBusyPct','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-API-Comments', 'narthur26', 'ServerTooBusyPct','GAUGE', 'http://www.bbc.co.uk','ms'
exec AddKPIConfig 'DNA-API-Comments', 'narthur27', 'ServerTooBusyPct','GAUGE', 'http://www.bbc.co.uk','ms'


/*
exec ChangeKPIThresholds 'DNA-RipleyServer', 'narthur1', 'AverageRequestTime','debug',null,null
exec ChangeKPIThresholds 'DNA-RipleyServer', 'narthur1', 'AverageRequestTime','info',null,null
exec ChangeKPIThresholds 'DNA-RipleyServer', 'narthur1', 'AverageRequestTime','warning',null,null
exec ChangeKPIThresholds 'DNA-RipleyServer', 'narthur1', 'AverageRequestTime','error',null,null
exec ChangeKPIThresholds 'DNA-RipleyServer', 'narthur1', 'AverageRequestTime','critical',null,null
*/