<!DOCTYPE xsl:stylesheet [
	<!ENTITY nbsp "&#160;">
]>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:msxsl="urn:schemas-microsoft-com:xslt" xmlns:local="#local-functions" xmlns:s="urn:schemas-microsoft-com:xml-data" xmlns:dt="urn:schemas-microsoft-com:datatypes" exclude-result-prefixes="msxsl local s dt">
	
<xsl:variable name="user_intro_fields">
	<![CDATA[<MULTI-INPUT>
		<REQUIRED NAME='TYPE'></REQUIRED>
		<REQUIRED NAME='BODY'></REQUIRED>
		<REQUIRED NAME='TITLE'></REQUIRED>
		<ELEMENT NAME='SPORTINGINTEREST1'><VALIDATE TYPE='EMPTY'/></ELEMENT>
		<ELEMENT NAME='SPORTINGINTEREST2'></ELEMENT>
		<ELEMENT NAME='SPORTINGINTEREST3'></ELEMENT>
		<ELEMENT NAME='FAVOURITEPLAYER'><VALIDATE TYPE='EMPTY'/></ELEMENT>
		<ELEMENT NAME='TEAMPLAYEDIN'></ELEMENT>
		<ELEMENT NAME='TEAMPLAYEDINLINK'></ELEMENT>
		<ELEMENT NAME='FAVOURITEMATCH'><VALIDATE TYPE='EMPTY'/></ELEMENT>
		<ELEMENT NAME='FAVOURITEMATCHLINK'></ELEMENT>
		<ELEMENT NAME='EXTERNALLINK1'></ELEMENT>
		<ELEMENT NAME='EXTERNALLINK1TITLE'></ELEMENT>
		<ELEMENT NAME='EXTERNALLINK2'></ELEMENT>
		<ELEMENT NAME='EXTERNALLINK2TITLE'></ELEMENT>
		<ELEMENT NAME='EXTERNALLINK3'></ELEMENT>
		<ELEMENT NAME='EXTERNALLINK3TITLE'></ELEMENT>
		
		<ELEMENT NAME='DATECREATED' EI='add'></ELEMENT>
		<ELEMENT NAME='LASTUPDATED' EI='add'></ELEMENT>
		<ELEMENT NAME='AUTHORNAME' EI='add'></ELEMENT>
		<ELEMENT NAME='AUTHORUSERID' EI='add'></ELEMENT>
		<ELEMENT NAME='AUTHORUSERNAME' EI='add'></ELEMENT>
		<ELEMENT NAME='TYPEOFARTICLE' ACTION='KEYPHRASE'></ELEMENT>
	</MULTI-INPUT>]]>
</xsl:variable>

<xsl:variable name="article_form">
	<![CDATA[<MULTI-INPUT>
		<REQUIRED NAME='TYPE'></REQUIRED> 
		<REQUIRED NAME='STATUS' EI='add'></REQUIRED>
		<REQUIRED NAME='BODY'><VALIDATE TYPE='EMPTY'/></REQUIRED>
		<REQUIRED NAME='TITLE'><VALIDATE TYPE='EMPTY'/></REQUIRED>
			
		<ELEMENT NAME='DATECREATED' EI='add'></ELEMENT>
		<ELEMENT NAME='DECLARATION_EMAIL' EI='add'></ELEMENT>
		<ELEMENT NAME='DECLARATION_LEGAL' EI='add'></ELEMENT>
		<ELEMENT NAME='DECLARATION_WARRANTY' EI='add'></ELEMENT>
		<ELEMENT NAME='DIRECTOR' EI='add'></element>
		<!-- <ELEMENT NAME='FILMTITLE' EI='add'></ELEMENT> -->
		<ELEMENT NAME='FIRSTNAME' EI='add'></ELEMENT>
		<ELEMENT NAME='GENRE' EI='add' ACTION='KEYPHRASE'><VALIDATE TYPE='EMPTY'/></ELEMENT>
		<ELEMENT NAME='GENRE01' EI='add' ACTION='KEYPHRASE'></ELEMENT>
		<ELEMENT NAME='GENRE02' EI='add' ACTION='KEYPHRASE'></ELEMENT>
		<ELEMENT NAME='GENRE03' EI='add' ACTION='KEYPHRASE'></ELEMENT>
		<ELEMENT NAME='IMAGE' EI='add'></ELEMENT>
		<ELEMENT NAME='LASTUPDATED' EI='add'></ELEMENT>
		<ELEMENT NAME='LENGTH_MIN' EI='add'><VALIDATE TYPE='EMPTY'/></ELEMENT>
		<ELEMENT NAME='LENGTH_SEC' EI='add'><VALIDATE TYPE='EMPTY'/></ELEMENT>
		<ELEMENT NAME='OTHER' EI='add' ACTION='KEYPHRASE'><VALIDATE TYPE='EMPTY'/></ELEMENT>
		<ELEMENT NAME='POLLTYPE1'></ELEMENT>
		<ELEMENT NAME='POLLTYPE1ALLOWANONYMOUSRATING'></ELEMENT> 
		<ELEMENT NAME='PUB_DAY' EI='add'><VALIDATE TYPE='EMPTY'/></ELEMENT>
		<ELEMENT NAME='PUB_MONTH' EI='add'><VALIDATE TYPE='EMPTY'/></ELEMENT>
		<ELEMENT NAME='PUB_YEAR' EI='add'><VALIDATE TYPE='EMPTY'/></ELEMENT>
		<ELEMENT NAME='RELATEDLINKS'></ELEMENT>
		<ELEMENT NAME='SCENE' EI='add' ACTION='KEYPHRASE'></ELEMENT>
		<ELEMENT NAME='SITELOCATION' EI='add'></ELEMENT>
		<ELEMENT NAME='SURNAME' EI='add'></ELEMENT>
		<ELEMENT NAME='SYNOPSIS' EI='add'></ELEMENT>
		<ELEMENT NAME='TAGLINE' EI='add'><VALIDATE TYPE='EMPTY'/></element>
		<ELEMENT NAME='THUMBNAIL' EI='add'></ELEMENT>
		<ELEMENT NAME='THEME' EI='add' ACTION='KEYPHRASE'><VALIDATE TYPE='EMPTY'/></ELEMENT>
		<ELEMENT NAME='VIDEOLINK'></ELEMENT>
		<ELEMENT NAME='BBCVIDEOLINK'></ELEMENT>

		<!-- right column elements -->
		<ELEMENT NAME='RIGHTCOL_BROWSE'></ELEMENT>
		<ELEMENT NAME='RIGHTCOL_TIPS'></ELEMENT>
		<ELEMENT NAME='RIGHTCOL_LINKS'></ELEMENT>
		<ELEMENT NAME='DYNAMICLIST'></ELEMENT>
		<ELEMENT NAME='RIGHTCOL_SUBMIT'></ELEMENT>
		
		<!-- tag phrases -->
		<ELEMENT NAME='TYPEOFARTICLE' EI='add' ACTION='KEYPHRASE'></ELEMENT>


	</MULTI-INPUT>]]>
</xsl:variable>

<xsl:variable name="editorial_article_fields">
	<![CDATA[<MULTI-INPUT>
		<REQUIRED NAME='TYPE'></REQUIRED>
		<REQUIRED NAME='BODY'><VALIDATE TYPE='EMPTY'/></REQUIRED>
		<REQUIRED NAME='TITLE'><VALIDATE TYPE='EMPTY'/></REQUIRED>
		<ELEMENT NAME='DATECREATED' EI='add'></ELEMENT>
		

		<ELEMENT NAME='DATECREATED' EI='add'></ELEMENT>
		<ELEMENT NAME='LASTUPDATED' EI='add'></ELEMENT>
		<ELEMENT NAME='AUTHORNAME' EI='add'></ELEMENT>
		<ELEMENT NAME='AUTHORUSERID' EI='add'></ELEMENT>
		<ELEMENT NAME='AUTHORUSERNAME' EI='add'></ELEMENT>
		<ELEMENT NAME='IMAGE' EI='add'></ELEMENT>

		<!-- right column elements -->
		<ELEMENT NAME='RIGHTCOL_BROWSE'></ELEMENT>
		<ELEMENT NAME='RIGHTCOL_TIPS'></ELEMENT>
		<ELEMENT NAME='RIGHTCOL_LINKS'></ELEMENT>
		<ELEMENT NAME='DYNAMICLIST'></ELEMENT>
		<ELEMENT NAME='RIGHTCOL_SUBMIT'></ELEMENT>

	</MULTI-INPUT>]]>
</xsl:variable>
</xsl:stylesheet>