CREATE PROCEDURE addtotempuserlist 
		@uid uniqueidentifier = NULL,
		@userid1 int = NULL,
		@userid2 int = NULL,
		@userid3 int = NULL,
		@userid4 int = NULL,
		@userid5 int = NULL,
		@userid6 int = NULL,
		@userid7 int = NULL,
		@userid8 int = NULL,
		@userid9 int = NULL,
		@userid10 int = NULL,
		@userid11 int = NULL,
		@userid12 int = NULL,
		@userid13 int = NULL,
		@userid14 int = NULL,
		@userid15 int = NULL,
		@userid16 int = NULL,
		@userid17 int = NULL,
		@userid18 int = NULL,
		@userid19 int = NULL,
		@userid20 int = NULL,
		@userid21 int = NULL,
		@userid22 int = NULL,
		@userid23 int = NULL,
		@userid24 int = NULL,
		@userid25 int = NULL,
		@userid26 int = NULL,
		@userid27 int = NULL,
		@userid28 int = NULL,
		@userid29 int = NULL,
		@userid30 int = NULL,
		@userid31 int = NULL,
		@userid32 int = NULL,
		@userid33 int = NULL,
		@userid34 int = NULL,
		@userid35 int = NULL,
		@userid36 int = NULL,
		@userid37 int = NULL,
		@userid38 int = NULL,
		@userid39 int = NULL,
		@userid40 int = NULL,
		@userid41 int = NULL,
		@userid42 int = NULL,
		@userid43 int = NULL,
		@userid44 int = NULL,
		@userid45 int = NULL,
		@userid46 int = NULL,
		@userid47 int = NULL,
		@userid48 int = NULL,
		@userid49 int = NULL,
		@userid50 int = NULL
as
IF @uid IS NULL
BEGIN
	select @uid = newid()
END
	insert into TempUserList (UID, UserID)
		SELECT @uid, UserID FROM Users WHERE UserID IN (
			@userid1,
			@userid2,
			@userid3,
			@userid4,
			@userid5,
			@userid6,
			@userid7,
			@userid8,
			@userid9,
			@userid10,
			@userid11,
			@userid12,
			@userid13,
			@userid14,
			@userid15,
			@userid16,
			@userid17,
			@userid18,
			@userid19,
			@userid20,
			@userid21,
			@userid22,
			@userid23,
			@userid24,
			@userid25,
			@userid26,
			@userid27,
			@userid28,
			@userid29,
			@userid30,
			@userid31,
			@userid32,
			@userid33,
			@userid34,
			@userid35,
			@userid36,
			@userid37,
			@userid38,
			@userid39,
			@userid40,
			@userid41,
			@userid42,
			@userid43,
			@userid44,
			@userid45,
			@userid46,
			@userid47,
			@userid48,
			@userid49,
			@userid50
			)

	select 'UID' = @uid
