Create Procedure getarticlesubjects	@id1 int = NULL,
										@id2 int = NULL,
										@id3 int = NULL,
										@id4 int = NULL,
										@id5 int = NULL,
										@id6 int = NULL,
										@id7 int = NULL,
										@id8 int = NULL,
										@id9 int = NULL,
										@id10 int = NULL,
										@id11 int = NULL,
										@id12 int = NULL,
										@id13 int = NULL,
										@id14 int = NULL,
										@id15 int = NULL,
										@id16 int = NULL,
										@id17 int = NULL,
										@id18 int = NULL,
										@id19 int = NULL,
										@id20 int = NULL,
										@id21 int = NULL,
										@id22 int = NULL,
										@id23 int = NULL,
										@id24 int = NULL,
										@id25 int = NULL,
										@id26 int = NULL,
										@id27 int = NULL,
										@id28 int = NULL,
										@id29 int = NULL,
										@id30 int = NULL,
										@id31 int = NULL,
										@id32 int = NULL,
										@id33 int = NULL,
										@id34 int = NULL,
										@id35 int = NULL,
										@id36 int = NULL,
										@id37 int = NULL,
										@id38 int = NULL,
										@id39 int = NULL,
										@id40 int = NULL,
										@id41 int = NULL,
										@id42 int = NULL,
										@id43 int = NULL,
										@id44 int = NULL,
										@id45 int = NULL,
										@id46 int = NULL,
										@id47 int = NULL,
										@id48 int = NULL,
										@id49 int = NULL,
										@id50 int = NULL,
										@id51 int = NULL,
										@id52 int = NULL,
										@id53 int = NULL,
										@id54 int = NULL,
										@id55 int = NULL,
										@id56 int = NULL,
										@id57 int = NULL,
										@id58 int = NULL,
										@id59 int = NULL,
										@id60 int = NULL,
										@id61 int = NULL,
										@id62 int = NULL,
										@id63 int = NULL,
										@id64 int = NULL,
										@id65 int = NULL,
										@id66 int = NULL,
										@id67 int = NULL,
										@id68 int = NULL,
										@id69 int = NULL,
										@id70 int = NULL,
										@id71 int = NULL,
										@id72 int = NULL,
										@id73 int = NULL,
										@id74 int = NULL,
										@id75 int = NULL,
										@id76 int = NULL,
										@id77 int = NULL,
										@id78 int = NULL,
										@id79 int = NULL,
										@id80 int = NULL,
										@id81 int = NULL,
										@id82 int = NULL,
										@id83 int = NULL,
										@id84 int = NULL,
										@id85 int = NULL,
										@id86 int = NULL,
										@id87 int = NULL,
										@id88 int = NULL,
										@id89 int = NULL,
										@id90 int = NULL,
										@id91 int = NULL,
										@id92 int = NULL,
										@id93 int = NULL,
										@id94 int = NULL,
										@id95 int = NULL,
										@id96 int = NULL
As
	SELECT 'Subject' = CASE
			WHEN Hidden IS NOT NULL THEN '' ELSE 
			CASE Subject WHEN '' THEN 'No Subject' ELSE Subject END
			END, EntryID, h2g2ID FROM GuideEntries
		WHERE h2g2ID IN (@id1, @id2, @id3, @id4, @id5, @id6, @id7, @id8, 
							@id9, @id10, @id11, @id12, @id13, @id14, @id15, @id16,
							@id17, @id18, @id19, @id20, @id21, @id22, @id23, @id24, 
							@id25, @id26, @id27, @id28, @id29, @id30, @id31, @id32,
							@id33, @id34, @id35, @id36, @id37, @id38, @id39, @id40, 
							@id41, @id42, @id43, @id44, @id45, @id46, @id47, @id48, 
							@id49, @id50, @id51, @id52, @id53, @id54, @id55, @id56, 
							@id57, @id58, @id59, @id60, @id61, @id62, @id63, @id64, 
							@id65, @id66, @id67, @id68, @id69, @id70, @id71, @id72, 
							@id73, @id74, @id75, @id76, @id77, @id78, @id79, @id80, 
							@id81, @id82, @id83, @id84, @id85, @id86, @id87, @id88, 
							@id89, @id90, @id91, @id92, @id93, @id94, @id95, @id96) 
	return (0)