-- This script takes a spreadsheet send to Mark N from Paul Wakely on 7th April 2011
-- with lots of changes to the "BBCDivisionId" in the sites table
--
-- It stuffs the changes in a table (__prodUpdate), then uses that to update the sites
-- table appropriately

-- 
if (object_id('__prodUpdate')) is not null
	drop table __prodUpdate
go

create table __prodUpdate
(
	siteid int,
	urlname varchar(50),
	shortdesc varchar(200),
	product varchar(50)
)

-- Insert data from Paul's spreadsheet into a table
insert __prodUpdate (siteid,urlname,shortdesc,product) values(79,'blog51','pmblog','Audio and Music')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(81,'blog96','ipmblog','Audio and Music')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(88,'blog35','blogfivelivebreakfast','Audio and Music')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(95,'blog63','blogchartblog','Audio and Music')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(96,'blog45','blogchrisevans','Audio and Music')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(98,'blog17','blogintroducing','Audio and Music')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(99,'blog96old','blogipm','Audio and Music')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(100,'blog102','blogjowhiley','Audio and Music')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(105,'blog50','blogmistajam','Audio and Music')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(112,'blog51old','blogpm','Audio and Music')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(113,'blog40','blogpodsandblogs','Audio and Music')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(116,'blog49','blogrussellbrand','Audio and Music')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(120,'blog30','blogthechrismoylesshow','Audio and Music')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(123,'blog88','blogvictoriaderbyshire','Audio and Music')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(125,'blog92','blogworldtonight','Audio and Music')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(131,'blog117','blog Bobby Friction','Audio and Music')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(146,'blog135','blogbollywood','Audio and Music')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(149,'blog138','blogradio2folk','Audio and Music')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(150,'blog144','blogstevelamacq','Audio and Music')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(159,'blog148','bloggregjames','Audio and Music')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(173,'blog167','blogradio4comedy','Audio and Music')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(196,'blog184','blogelectricproms','Audio and Music')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(207,'blog212','blogzanelowe','Audio and Music')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(226,'blog233','blogcoty2009','Audio and Music')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(228,'blog235','blogradio4','Audio and Music')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(229,'blog236','blogadilrayshow','Audio and Music')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(233,'blog240','blog1xtrabreakfast','Audio and Music')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(249,'blog183','blogbbcmusic','Audio and Music')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(274,'blog293','blogradio3','Audio and Music')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(285,'blog305','blogrampage','Audio and Music')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(287,'blog314','blogadamandjoe','Audio and Music')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(288,'blog313','blogscottmills','Audio and Music')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(361,'blog217','blogradio1movies','Audio and Music')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(373,'blog449','blogahistoryoftheworld','Audio and Music')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(375,'blog451','blogsimonmayo','Audio and Music')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(381,'blog459','bloglaurenlaverne','Audio and Music')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(399,'blog486','blogthearchers','Audio and Music')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(400,'blog487','blogambridgevillage','Audio and Music')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(401,'blog488','blogyouandyours','Audio and Music')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(410,'blog497','blogjarviscocker','Audio and Music')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(414,'blog501','blogtomrobinson','Audio and Music')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(450,'blog542','blogoutriders','Audio and Music')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(454,'blog543','blogblogparty','Audio and Music')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(457,'blog546','blogJamieCullum','Audio and Music')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(480,'blog568','radio','Audio and Music')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(18,'mb6music','6 Music','Audio and Music')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(26,'mbradio2','Radio 2','Audio and Music')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(31,'mbasiannetwork','Asian Network','Audio and Music')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(46,'mbbbc7','Radio 7','Audio and Music')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(53,'mbarchers','Archers','Audio and Music')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(61,'mbradio4','Radio 4','Audio and Music')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(452,'radio4','radio4','Audio and Music')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(75,'c6music','c6music','Audio and Music')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(216,'hogmanay','hogmanay','Audio and Music')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(238,'musicreviews','musicreviews','Audio and Music')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(258,'U2attheBBC','U2attheBBC','Audio and Music')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(281,'radioonebw','radioonebw','Audio and Music')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(284,'bbcintroducing','bbcintroducing','Audio and Music')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(298,'glastonbury2009','glastonbury2009','Audio and Music')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(301,'promsreviews','promsreviews','Audio and Music')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(313,'mercuryprize','mercuryprize','Audio and Music')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(314,'cambridgefolkfestival09','cambridgefolkfestival09','Audio and Music')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(321,'radio1','radio1','Audio and Music')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(337,'readingandleeds09','readingandleeds09','Audio and Music')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(344,'1x','1x','Audio and Music')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(365,'great-british-songbook','great-british-songbook','Audio and Music')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(366,'ahistoryoftheworld','ahistoryoftheworld','Audio and Music')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(369,'radio2','radio2','Audio and Music')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(383,'inourtime','inourtime','Audio and Music')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(384,'radio3','radio3','Audio and Music')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(416,'6music','6music','Audio and Music')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(439,'asiannetwork','asiannetwork','Audio and Music')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(453,'glastonbury','glastonbury','Audio and Music')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(463,'iplayerradio','iplayerradio','Audio and Music')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(89,'blog90','blogaceandvis','Audio and Music')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(481,'blog569','talkback','Audio and Music')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(503,'blog589','New Comedy Awards','Audio and Music')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(505,'blog592','Eurovision','Audio and Music')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(451,'bigmexicanwave','bigmexicanwave','Audio and Music')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(488,'BBCSoundOf2011','BBCSoundOf2011','Audio and Music')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(497,'bbcproms','bbcproms','Audio and Music')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(158,'blog147','blogacrosstheline','Audio and Music')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(328,'blog407','5live','Audio and Music')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(343,'blog399','blogwalesmusic','Audio and Music')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(417,'blog504','blogradioscotland','Audio and Music')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(393,'scotlandsmusic','scotlandsmusic','Audio and Music')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(334,'stephennolan','stephennolan','Audio and Music')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(54,'mbcbbc','mbCBBC','Childrens')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(55,'mbcbeebies','CBeebies','Childrens')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(57,'mbnewsround','Newsround','Childrens')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(484,'blog575','cbeebiesgrownups','Childrens')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(91,'blog101','blogbbcinternet','FM&T')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(114,'blog100','blogradiolabs','FM&T')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(231,'blog238','blograd','FM&T')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(269,'blog286','blogspacesandplaces','FM&T')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(335,'blog389','aboutthebbc','FM&T')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(362,'blog433','blogresearchanddevelopment','FM&T')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(394,'blog478','blogbackstage','FM&T')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(445,'blog525','blogdeveloper','FM&T')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(327,'blog379','neilreynolds','FM&T')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(70,'mbiplayer','mbiplayer','FM&T')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(1,'h2g2','h2g2','FM&T')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(2,'dev','dev','FM&T')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(8,'hub','DNA Hub','FM&T')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(66,'moderation','moderation','FM&T')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(444,'flowsocialcore','flowsocialcore','FM&T')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(71,'memoryshare','memoryshare','FM&T')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(41,'mbonionstreet','mbonionstreet','K&Lfunded')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(306,'blog349','blogblast','K&Lfunded')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(73,'mbks3bitesize','mbgcsebitesize','K&Lfunded')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(74,'mbgcsebitesize','mbgcsebitesize','K&Lfunded')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(78,'mbstudentlife','mbstudentlife','K&Lfunded')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(110,'blog16','blogouch','Knowledge and Learning')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(127,'blog74','blogwritersroom','Knowledge and Learning')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(135,'blog121','blog Mark Kermode','Knowledge and Learning')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(230,'blog237','blogadamcurtis','Knowledge and Learning')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(441,'blog534','blognatureuk','Knowledge and Learning')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(460,'blog550','blogfood','Knowledge and Learning')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(468,'blog558','blogparents','Knowledge and Learning')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(478,'blog566','gardening','Knowledge and Learning')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(495,'blog585','23degrees','Knowledge and Learning')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(35,'mbreligion','Religion','Knowledge and Learning')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(36,'mbhistory','History','Knowledge and Learning')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(40,'mbouch','Ouch!','Knowledge and Learning')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(49,'mbfood','Food','Knowledge and Learning')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(58,'mbparents','Parents','Knowledge and Learning')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(60,'mbgardening','Gardening','Knowledge and Learning')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(434,'slink','slink','Knowledge and Learning')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(352,'filmnetwork-identity','filmnetwork','Knowledge and Learning')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(502,'blog588','Webwise','Knowledge and Learning')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(511,'blog597','Wonder Monkey','Knowledge and Learning')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(412,'blog499','blogwaleshistory','Knowledge and Learning')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(268,'forteachers','forteachers','Knowledge and Learning')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(130,'blog116','blog Chelsea Flower Show','Knowledge and Learning')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(133,'blog119','blog Gardeners'' World - Alys Fowler','Knowledge and Learning')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(134,'blog120','blog Gardeners'' World - Joe Swift','Knowledge and Learning')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(477,'mbnatureuk','Nature UK','Knowledge and Learning')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(20,'filmnetwork','filmnetwork','Knowledge and Learning')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(349,'headroom','headroom','Knowledge and Learning')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(189,'blog190','bloggwtobybuckland','Knowledge and Learning')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(227,'blog234','blogclimatechange','Knowledge and Learning')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(275,'blog294','blogdigin','Knowledge and Learning')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(220,'blog227','blogjanecorbin','News')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(222,'blog229','blogoldrichardmoss','News')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(223,'blog230','blogolddaveharvey','News')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(224,'blog231','blogolddavidgregory','News')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(264,'blog267','blogpressred','News')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(300,'blog340','scotlandsmusic','News')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(307,'blog350','ianfergusson','News')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(311,'blog357','blogsteveparry','News')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(317,'blog364','blogmarkclemmit','News')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(351,'blog412','blogjohnmaxwellhobbs','News')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(357,'blog421','blogjoecrowley','News')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(358,'blog431','blogfranzstrasser','News')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(359,'blog432','blogianpannell','News')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(367,'blog440','blogpeoplespolitican','News')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(368,'blog441','blogseealso','News')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(374,'blog450','blogsberniekeith','News')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(378,'blog455','blogjersey','News')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(386,'blog463','blogtimiredale','News')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(403,'blog492','blogjohnbarclay','News')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(415,'blog502','blogrealitycheck','News')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(419,'blog507','blogtimdonovan','News')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(423,'blog511','blogsoundwaves','News')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(426,'blog517','blogjohnhess','News')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(433,'blog527','blogworldcupphotoalbum','News')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(435,'blog528','blogbrunosenna','Sport')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(442,'blog535','blogwillsmith','News')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(456,'blog544','blogwhocares','News')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(466,'blog554','blogkentintroducing','Audio and Music')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(467,'blog555','blogbeckywant','News')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(482,'blog573','nickbooth','News')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(101,'blog104','blogjustinwebbsamerica','News')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(103,'blog83','blogmarkmardellseuroblog','News')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(356,'journalism-local','journalismlocal','News')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(382,'videonation','videonation','News')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(92,'blog82','blogbetsansblog','News')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(93,'blog81','blogbletherwithbrian','News')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(97,'blog103','blogdotlife','News')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(102,'blog55','blogmagazinemonitor','News')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(106,'blog98','blognickbryantsaustralia','News')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(107,'blog9','blognickrobinsonsnewslog','News')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(109,'blog28','blogopensecrets','News')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(111,'blog69','blogpestonspicks','News')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(115,'blog60','blogradioulster','Audio and Music')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(118,'blog8','blognewsnight','News')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(121,'blog80','blogthedevenportdiaries','News')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(122,'blog23','blogtheeditors','News')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(124,'blog14','blogwillandtestament','News')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(136,'blog126','blog Wales Nature','Knowledge and Learning')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(140,'blog130','blogpaulinemclean','News')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(147,'blog136','blogmarkeaston','News')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(151,'blog139','blogmichaelcrick','News')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(152,'blog141','blogmarkurban','News')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(153,'blog140','blogpaulmason','News')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(154,'blog142','blognewsnightproduction','News')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(157,'blog146','blogbriansblog','News')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(177,'blog172','blogpanorama','News')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(178,'blog173','blogtomfeilden','News')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(190,'blog185','blogandrewneil','News')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(195,'blog197','blogsusanwatts','News')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(197,'blog198','blogrichardblack','News')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(198,'blog199','blogworkinglunch','News')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(209,'blog215','blogdouglasfraser','News')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(214,'blog222','blogwalesarts','News')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(235,'blog242','blogstephanieflanders','News')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(246,'blog252','blogethicalman','News')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(276,'blog298','blogphoto','News')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(277,'blog299','blogindiaelection09','News')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(283,'blog285','blogcollegeofjournalism','News')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(286,'blog307','blogfluwatch','News')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(294,'blog325','blogdavidgregory','News')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(295,'blog326','blogdaveharvey','News')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(296,'blog327','blogrichardmoss','News')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(299,'blog344','scotlandlearning','Knowledge and Learning')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(312,'blog358','blogjonathanamos','News')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(319,'blog365','blogartsextra','News')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(320,'blog366','blogbradleys','News')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(323,'blog375','kurtbarling','News')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(325,'blog377','markdarcy','News')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(338,'blog392','markmardell','News')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(340,'blog394','bloggavinhewitt','News')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(341,'blog397','blogpeterhenley','News')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(346,'blog402','blogchrisjackson','News')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(355,'blog420','blogpaulhudson','News')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(379,'blog456','blogrorycellanjones','News')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(380,'blog457','blogmaggieshiels','News')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(385,'blog462','bloglentingle','News')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(388,'blog471','blogpatrickburns','News')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(389,'blog470','blogdavidcornock','News')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(402,'blog491','blogwillgompertz','News')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(408,'blog496','blogarifansari','News')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(418,'blog506','blogmarkcummings','News')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(420,'blog508','bloggrahamsmith','News')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(421,'blog509','blogguysmith','News')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(424,'blog515','blogpaulbarltrop','News')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(425,'blog516','blogdeborahmcgurran','News')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(427,'blog518','blogmartynoates','News')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(428,'blog519','Andrew Harding''s Africa','News')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(431,'blog524','blogmindthegap','News')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(448,'blog538','blogannediamond','News')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(458,'blog547','blogmattfrei','News')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(483,'blog574','louisestewart','News')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(390,'blog473','blogjackross','News')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(479,'blog567','steveclaridge','News')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(392,'blog477','bloghaveyoursay','News')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(492,'newscommentsmodule','newscommentsmodule','News')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(119,'blog44','blogtestmatchspecial','Sport')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(165,'blog158','bloggolf','Sport')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(166,'blog159','blogyouaretheref','Sport')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(247,'blog253','blogrugby','Sport')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(117,'blog20','blogsporteditorsblog','Sport')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(137,'blog127','blog NW200','Sport')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(160,'blog154','blogsportchrischarles','Sport')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(164,'blog157','blogsportpaulfletcher','Sport')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(172,'blog166','blogstevewilson','Sport')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(183,'blog178','blogjacquioatley','Sport')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(193,'blog193','bloggavinstrachan','Sport')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(244,'blog249','blogf1mole','Sport')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(254,'blog255','blogkatharinemerry','Sport')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(262,'blog265','blogjonathanlegard','Sport')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(270,'blog287','blogmatthewpinsent','Sport')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(271,'blog288','blogrishipersad','Sport')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(279,'blog301','blogwillclarke','Sport')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(289,'blog317','blogbethrodford','Sport')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(290,'blog316','blogmartingough','Sport')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(291,'blog318','blogannabelvernon','Sport')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(297,'blog331','blogsonjamclaughlan','Sport')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(326,'blog378','jimneilly','Sport')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(330,'blog381','annathompson','Sport')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(395,'blog482','bloggeorgeriley','Sport')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(396,'blog483','blogleighgriffiths','Sport')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(411,'blog498','blogebonyrainfordbrent','Sport')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(432,'blog526','bloggaryinnes','Sport')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(437,'blog529','blogjenniegow','Sport')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(443,'blog536','blogworldcupmotty','Sport')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(472,'blog560','blogmarkchapman','Sport')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(475,'blog564','blogstephenwatson','Sport')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(38,'mb606','mb606','Sport')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(129,'blog115','blog Olympics','Sport')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(219,'blog226','blographaelrowe','Sport')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(316,'blog362','blogjoeltaggart','Sport')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(161,'blog152','blogsportphilmcnulty','Sport')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(162,'blog155','blogsportrobborobson','Sport')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(167,'blog160','blogtimvickery','Sport')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(169,'blog162','blogiaincarter','Sport')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(170,'blog163','blogrobhodgetts','Sport')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(202,'blog206','blogmattslater','Sport')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(203,'blog207','blogtomfordyce','Sport')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(204,'blog208','blogbendirs','Sport')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(205,'blog209','blogandrewbenson','Sport')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(206,'blog210','blogchrisjardine','Sport')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(232,'blog239','blogjonathanoverend','Sport')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(243,'blog248','blogbrynpalmer','Sport')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(253,'blog254','bloggordonfarquhar','Sport')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(255,'blog256','blogadrianwarner','Sport')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(261,'blog264','blogjakehumphrey ','Sport')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(263,'blog266','blogmurraywalker','Sport')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(272,'blog289','blogjimspence','Sport')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(302,'blog345','adammountford','Sport')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(303,'blog346','alisonmitchell','Sport')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(304,'blog347','oliverbrett','Sport')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(305,'blog348','rogermosey','Sport')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(310,'blog355','blogolliewilliams','Sport')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(324,'blog376','danwalker','Sport')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(331,'blog382','chrisbevan','Sport')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(339,'blog393','blogphilminshull','Sport')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(342,'blog398','blogeleanoroldroyd','Sport')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(372,'blog448','blogpiersedwards','Sport')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(376,'blog453','blogjohnbeattie','Sport')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(377,'blog454','blogsarahholt','Sport')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(397,'blog484','blogmartinlaird','Sport')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(398,'blog485','blogjamespearce','Sport')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(422,'blog510','blogdavidbond','Sport')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(430,'blog521','blogdanroan','Sport')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(449,'blog539','blogaustinocallaghan','Sport')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(459,'blog532','blogworldcup','Sport')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(476,'blog565','special1','Sport')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(498,'blog587','thefootballtacticsblog','Sport')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(67,'606','606','Sport')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(267,'blog269','blogsteveaustin','Sport')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(496,'blog586','bloglatekickoff','Sport')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(506,'blog593','Matt Roberts','Sport')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(509,'blog594','Tim Franks','Sport')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(447,'joeydunlop','joeydunlop','Sport')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(371,'blog445','blogx-ray','TV/iPlayer')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(186,'blog180','blogrivercity','TV/iPlayer')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(174,'blog168','blogoneshowcomsumer','TV/iPlayer')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(213,'blog221','blogbeinghuman','TV/iPlayer')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(239,'blog243','blogcomedy','TV/iPlayer')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(278,'blog182','blogseehear','TV/iPlayer')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(348,'blog404','blogrussellhoward','TV/iPlayer')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(364,'blog434','blogtheoneshow','TV/iPlayer')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(370,'blog443','blogeastenders','TV/iPlayer')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(387,'blog469','blogbbcthree','TV/iPlayer')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(391,'blog474','blogtv','TV/iPlayer')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(490,'blog578','becominghuman','TV/iPlayer')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(19,'mbpointsofview','P.O.V.','TV/iPlayer')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(191,'blog191','blogwatchdog','TV/iPlayer')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(494,'blog583','waterlooroadreunited','TV/iPlayer')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(280,'comedyextraidentity','comedyextraidentity','TV/iPlayer')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(318,'dragonsden','dragonsden','TV/iPlayer')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(409,'buzzindex','buzzindex','TV/iPlayer')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(446,'iplayertv','iplayertv','TV/iPlayer')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(141,'blog131','blogtvplatforms','TV/iPlayer')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(176,'blog170','blogoneshowproduction','TV/iPlayer')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(250,'theapprentice','theapprentice','TV/iPlayer')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(251,'apprentice','apprentice','TV/iPlayer')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(252,'electricdreams','electricdreams','TV/iPlayer')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(266,'comedyextra','comedyextra','TV/iPlayer')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(175,'blog169','blogoneshowpassions','TV/iPlayer')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(180,'blog175','bloglastchancetosee','TV/iPlayer')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(491,'collegeofproduction','collegeofproduction','Undefined')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(145,'blog134','blogcultureshow','Vision')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(259,'blog261','blogknowledgeexchange','Vision')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(126,'blog12','blogworldupdatewithdandamon','World Service')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(404,'blog475','blogrussellfuller','World Service')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(210,'blog214','blogworldhaveyoursay- closed','World Service')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(329,'blog189','blogovertoyou','World Service')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(347,'blog405','bloginternetcafehobo','World Service')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(406,'blog493','blogblogworld','World Service')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(407,'blog495','bloglearningenglish','World Service')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(429,'blog520','writerinresidence','World Service')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(489,'blog576','worldclass','World Service')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(56,'mble','Learning English','World Service')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(248,'blog216','blogworldhaveyoursay','WSINT')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(436,'learningenglish','learningenglish','World Service')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(440,'blog533','blogafricahaveyoursay','WSINT')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(493,'blog582','blogfocusonafrica','World Service')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(499,'wsmundo','wsmundo','WSINT')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(500,'wsarabic','wsarabic','WSINT')
insert __prodUpdate (siteid,urlname,shortdesc,product) values(501,'wsportuguese','wsportuguese','WSINT')

-- Insert the missing "products" into bbcdivision table
;with newProds as
(
	select distinct pu.product
	from __prodUpdate pu
	left join bbcdivision bd on pu.product=bd.bbcdivisionname
	where bd.bbcdivisionname is null
)
insert bbcdivision(bbcdivisionname) select product from newProds


-- Update all the sites that should belong to a different bbc division
begin tran

;with sitesToUpdate as
(
	select s.siteid, s.bbcdivisionid, bd2.bbcdivisionid as newDivId
	from sites s
	join __prodUpdate pu on s.siteid = pu.siteid
	join bbcdivision bd on s.bbcdivisionid=bd.bbcdivisionid
	join bbcdivision bd2 on pu.product=bd2.bbcdivisionname
	where bd.bbcdivisionname <> pu.product
)
update sitesToUpdate
	Set bbcdivisionid = newDivId

commit tran
go

-- Clean up by dropping this table
if (object_id('__prodUpdate')) is not null
	drop table __prodUpdate
go


/*
select s.bbcdivisionid,bbcdivisionname,* from sites s
	join bbcdivision bd on s.bbcdivisionid=bd.bbcdivisionid


select s.siteid, s.bbcdivisionid, bd2.bbcdivisionid as newDivId
from sites s
join __prodUpdate pu on s.siteid = pu.siteid
join bbcdivision bd on s.bbcdivisionid=bd.bbcdivisionid
join bbcdivision bd2 on pu.product=bd2.bbcdivisionname
where bd.bbcdivisionname <> pu.product


SELECT * from __prodUpdate pu
join sites s on s.siteid=pu.siteid
left join bbcdivision bd on pu.product=bd.bbcdivisionname
where (s.urlname <> pu.urlname) or (bd.bbcdivisionname is null)

select * from bbcdivision
order by bbcdivisionid
*/