<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE xsl:stylesheet [
	<!ENTITY nbsp "&#160;">
]>
<xsl:stylesheet version="1.0"
	xmlns:xhtml="http://www.w3.org/1999/xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
	xmlns:msxsl="urn:schemas-microsoft-com:xslt"
	xmlns:local="#local-functions"
	xmlns:s="urn:schemas-microsoft-com:xml-data"
	xmlns:dt="urn:schemas-microsoft-com:datatypes"
	exclude-result-prefixes="msxsl local s dt xhtml">
	
<xsl:variable name="user_intro_fields">
	<![CDATA[<MULTI-INPUT>
		<REQUIRED NAME='TYPE'></REQUIRED>
		<REQUIRED NAME='BODY'><VALIDATE TYPE='EMPTY'/></REQUIRED>
		<REQUIRED NAME='TITLE'></REQUIRED>
		
		<ELEMENT NAME='DATECREATED' EI='add'></ELEMENT>
		<ELEMENT NAME='LASTUPDATED' EI='add'></ELEMENT>
		<ELEMENT NAME='AUTHORNAME' EI='add'></ELEMENT>
		<ELEMENT NAME='AUTHORUSERID' EI='add'></ELEMENT>
		<ELEMENT NAME='AUTHORUSERNAME' EI='add'></ELEMENT>
		
		<ELEMENT NAME='ARTICLECLASS' ACTION='KEYPHRASE'></ELEMENT>
	</MULTI-INPUT>]]>
</xsl:variable>

<xsl:variable name="article_form">
	<![CDATA[<MULTI-INPUT>
		<REQUIRED NAME='TYPE'></REQUIRED>
		<REQUIRED NAME='BODY'><VALIDATE TYPE='EMPTY'/></REQUIRED>
		<REQUIRED NAME='TITLE'><VALIDATE TYPE='EMPTY'/></REQUIRED>
		
		<REQUIRED NAME='STARTDATE' EI='add'><VALIDATE TYPE='EMPTY'/></REQUIRED>
		<REQUIRED NAME='STARTDAY' EI='add'></REQUIRED>
		<REQUIRED NAME='STARTMONTH' EI='add'></REQUIRED>
		<REQUIRED NAME='STARTYEAR' EI='add'></REQUIRED>
		<REQUIRED NAME='ENDDATE' EI='add'><VALIDATE TYPE='EMPTY'/></REQUIRED>
		<REQUIRED NAME='ENDDAY' EI='add'></REQUIRED>
		<REQUIRED NAME='ENDMONTH' EI='add'></REQUIRED>
		<REQUIRED NAME='ENDYEAR' EI='add'></REQUIRED>
				
		<REQUIRED NAME='TIMEINTERVAL' EI='add'></REQUIRED>
		
		<ELEMENT NAME='ARTICLELINK'></ELEMENT>
		<ELEMENT NAME='ARTICLELINKTITLE'></ELEMENT>
		<ELEMENT NAME='ARTICLEFORUMSTYLE'></ELEMENT>

		<ELEMENT NAME='ALTNAME' EI='add'></ELEMENT>	
		<ELEMENT NAME='LOCATION' EI='add' ACTION='KEYPHRASE'><VALIDATE TYPE='EMPTY'/></ELEMENT>
		<ELEMENT NAME='LOCATIONUSER' EI='add' ACTION='KEYPHRASE'></ELEMENT> 	
		<ELEMENT NAME='KEYWORDS' ACTION='KEYPHRASE' RAWINPUT='1'><VALIDATE TYPE='EMPTY'/></ELEMENT>

		<ELEMENT NAME='DATECREATED' EI='add'></ELEMENT>
		<ELEMENT NAME='LASTUPDATED' EI='add'></ELEMENT>
		<ELEMENT NAME='AUTHORNAME' EI='add'></ELEMENT>
		<ELEMENT NAME='AUTHORUSERID' EI='add'></ELEMENT>
		<ELEMENT NAME='AUTHORUSERNAME' EI='add'></ELEMENT>
		
		<ELEMENT NAME='ARTICLECLASS' EI='add' ACTION='KEYPHRASE'></ELEMENT>
		<ELEMENT NAME='TYPEOFARTICLE' EI='add' ACTION='KEYPHRASE'></ELEMENT>
		<ELEMENT NAME='CLIENT' ACTION='KEYPHRASE'></ELEMENT>
		<ELEMENT NAME='VISIBLECLIENT' ACTION='KEYPHRASE'></ELEMENT>
		
		<!-- fields for embedded media assets -->
		<!--
		<REQUIRED NAME='MIMETYPE'><VALIDATE TYPE='EMPTY'/></REQUIRED>
		<ELEMENT NAME='MEDIAASSETDESCRIPTION'><VALIDATE TYPE=''/></REQUIRED>
		<ELEMENT NAME='ORIGINYEAR'><VALIDATE TYPE=''/></ELEMENT>
		<ELEMENT NAME='ORIGINMONTH'><VALIDATE TYPE=''/></ELEMENT>
		<ELEMENT NAME='ORIGINDAY'><VALIDATE TYPE=''/></ELEMENT>
		<ELEMENT NAME='MIMETYPE'></ELEMENT>
		<ELEMENT NAME='CONTENTTYPE'><VALIDATE TYPE='EMPTY'/></ELEMENT>
		<ELEMENT NAME='MAUNUALUPLOAD'></ELEMENT>
		<ELEMENT NAME='EXTERNALLINK'></ELEMENT>
		<ELEMENT NAME='HASASSET'></ELEMENT>
		-->
		<ELEMENT NAME='EXTERNALLINKURL'></ELEMENT>
		<ELEMENT NAME='TERMSANDCONDITIONS'></ELEMENT>
	</MULTI-INPUT>]]>
	
</xsl:variable>

<xsl:variable name="editorial_article_fields">
	<![CDATA[<MULTI-INPUT>
		<REQUIRED NAME='TYPE'></REQUIRED>
		<REQUIRED NAME='BODY'><VALIDATE TYPE='EMPTY'/></REQUIRED>
		<REQUIRED NAME='TITLE'><VALIDATE TYPE='EMPTY'/></REQUIRED>
		<ELEMENT NAME='DATECREATED' EI='add'></ELEMENT>
		
		<ELEMENT NAME='INTROTEXT' EI='add'></ELEMENT>
		
		<ELEMENT NAME='DATECREATED' EI='add'></ELEMENT>
		<ELEMENT NAME='LASTUPDATED' EI='add'></ELEMENT>
		<ELEMENT NAME='AUTHORNAME' EI='add'></ELEMENT>
		<ELEMENT NAME='AUTHORUSERID' EI='add'></ELEMENT>
		<ELEMENT NAME='AUTHORUSERNAME' EI='add'></ELEMENT>
	</MULTI-INPUT>]]>
</xsl:variable>
</xsl:stylesheet>
