<!DOCTYPE xsl:stylesheet [
	<!ENTITY nbsp "&#160;">
]>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:msxsl="urn:schemas-microsoft-com:xslt" xmlns:local="#local-functions" xmlns:s="urn:schemas-microsoft-com:xml-data" xmlns:dt="urn:schemas-microsoft-com:datatypes" exclude-result-prefixes="msxsl local s dt">
	<xsl:variable name="clients">
		<list>
			<item>
			 	<name>London</name>
			 	<client>london</client>
			 	<visibletag>BBC London</visibletag>
			 	<url>http://www.bbc.co.uk/london/</url>
			 	<logo1>logos/logo1_london.gif</logo1>
			 	<rsshelp>http://www.bbc.co.uk/london/rss/</rsshelp>
			 	<css>
			 		<list>
			 			<item>/englandcms/style/common.css</item>
						<item>/englandcms/style/include_common.css</item>
						<item>/englandcms/style/index.css</item>
						
						<!-- server specific -->
						<item>css/common.css</item>
						<item>css/styles.css</item>
						<item>css/editor.css</item>
			 		</list>
			 	</css>
			 	<includes>
			 		<global>
			 			<list>
			 				<item>/englandcms/wil/includes/london/default.site</item>
			 				<item>/englandcms/wil/includes/london/default.section</item>
			 				<item>/global.page</item>
			 			</list>
			 		</global>
			 		<header>
			 			<list>
			 				<item>/header.page</item>
			 			</list>
			 		</header>
			 		<footer>
			 			<list>
			 				<item>/footer.page</item>
			 			</list>
			 		</footer>
			 	</includes>
			</item>
			<item>
			 	<name>Norfolk</name>
			 	<client>norfolk</client>
			 	<visibletag>BBC Norfolk</visibletag>
			 	<url>http://www.bbc.co.uk/norfolk/</url>
			 	<logo1>logos/logo1_norfolk.gif</logo1>
			 	<rsshelp>http://www.bbc.co.uk/norfolk/rss/</rsshelp>
			 	<css>
			 		<list>
			 			<item>/englandcms/style/common.css</item>
						<item>/englandcms/style/include_common.css</item>
						<item>/englandcms/style/index.css</item>
						
						<!-- server specific -->
						<item>css/common.css</item>
						<item>css/styles.css</item>
						<item>css/editor.css</item>
			 		</list>
			 	</css>
			 	<includes>
			 		<global>
			 			<list>
			 				<item>/englandcms/wil/includes/norfolk/default.site</item>
			 				<item>/englandcms/wil/includes/norfolk/default.section</item>
			 				<item>/global.page</item>
			 			</list>
			 		</global>
			 		<header>
			 			<list>
			 				<item>/header.page</item>
			 			</list>
			 		</header>
			 		<footer>
			 			<list>
			 				<item>/footer.page</item>
			 			</list>
			 		</footer>
			 	</includes>
			</item>
			<item>
			 	<name>South Yorkshire</name>
			 	<client>southyorkshire</client>
			 	<visibletag>BBC South Yorkshire</visibletag>
			 	<url>http://www.bbc.co.uk/southyorkshire/</url>
			 	<logo1>logos/logo1_southyorkshire.gif</logo1>
			 	<rsshelp>http://www.bbc.co.uk/feedfactory/help.shtml</rsshelp>
			 	<css>
			 		<list>
			 			<item>/englandcms/style/common.css</item>
						<item>/englandcms/style/include_common.css</item>
						<item>/englandcms/style/index.css</item>
						
						<!-- server specific -->
						<item>css/common.css</item>
						<item>css/styles.css</item>
						<item>css/editor.css</item>
			 		</list>
			 	</css>
			 	<includes>
			 		<global>
			 			<list>
			 				<item>/englandcms/wil/includes/southyorkshire/default.site</item>
			 				<item>/englandcms/wil/includes/southyorkshire/default.section</item>
			 				<item>/global.page</item>
			 			</list>
			 		</global>
			 		<header>
			 			<list>
			 				<item>/header.page</item>
			 			</list>
			 		</header>
			 		<footer>
			 			<list>
			 				<item>/footer.page</item>
			 			</list>
			 		</footer>
			 	</includes>
			 </item>
			 <item>
			 	<name>Cumbria</name>
			 	<client>cumbria</client>
			 	<visibletag>BBC Cumbria</visibletag>
			 	<url>http://www.bbc.co.uk/cumbria/</url>
			 	<logo1>logos/logo1_cumbria.gif</logo1>
			 	<rsshelp>http://www.bbc.co.uk/feedfactory/help.shtml</rsshelp>
			 	<css>
			 		<list>
			 			<item>/englandcms/style/common.css</item>
						<item>/englandcms/style/include_common.css</item>
						<item>/englandcms/style/index.css</item>
						
						<!-- server specific -->
						<item>css/common.css</item>
						<item>css/styles.css</item>
						<item>css/editor.css</item>
			 		</list>
			 	</css>
			 	<includes>
			 		<global>
			 			<list>
			 				<item>/englandcms/wil/includes/cumbria/default.site</item>
			 				<item>/englandcms/wil/includes/cumbria/default.section</item>
			 				<item>/global.page</item>
			 			</list>
			 		</global>
			 		<header>
			 			<list>
			 				<item>/header.page</item>
			 			</list>
			 		</header>
			 		<footer>
			 			<list>
			 				<item>/footer.page</item>
			 			</list>
			 		</footer>
			 	</includes>
			 </item>
			 <item>
			 	<name>Liverpool</name>
			 	<client>liverpool</client>
			 	<visibletag>BBC Liverpool</visibletag>
			 	<url>http://www.bbc.co.uk/liverpool/</url>
			 	<logo1>logos/logo1_liverpool.gif</logo1>
			 	<rsshelp>http://www.bbc.co.uk/feedfactory/help.shtml</rsshelp>
			 	<css>
			 		<list>
			 			<item>/englandcms/style/common.css</item>
						<item>/englandcms/style/include_common.css</item>
						<item>/englandcms/style/index.css</item>
						
						<!-- server specific -->
						<item>css/common.css</item>
						<item>css/styles.css</item>
						<item>css/editor.css</item>
			 		</list>
			 	</css>
			 	<includes>
			 		<global>
			 			<list>
			 				<item>/englandcms/wil/includes/liverpool/default.site</item>
			 				<item>/englandcms/wil/includes/liverpool/default.section</item>
			 				<item>/global.page</item>
			 			</list>
			 		</global>
			 		<header>
			 			<list>
			 				<item>/header.page</item>
			 			</list>
			 		</header>
			 		<footer>
			 			<list>
			 				<item>/footer.page</item>
			 			</list>
			 		</footer>
			 	</includes>
			 </item>
			 <item>
			 	<name>Derby</name>
			 	<client>derby</client>
			 	<visibletag>BBC Derby</visibletag>
			 	<url>http://www.bbc.co.uk/derby/</url>
			 	<logo1>logos/logo1_derby.gif</logo1>
			 	<rsshelp>http://www.bbc.co.uk/feedfactory/help.shtml</rsshelp>
			 	<css>
			 		<list>
			 			<item>/englandcms/style/common.css</item>
						<item>/englandcms/style/include_common.css</item>
						<item>/englandcms/style/index.css</item>
						
						<!-- server specific -->
						<item>css/common.css</item>
						<item>css/styles.css</item>
						<item>css/editor.css</item>
			 		</list>
			 	</css>
			 	<includes>
			 		<global>
			 			<list>
			 				<item>/englandcms/wil/includes/derby/default.site</item>
			 				<item>/englandcms/wil/includes/derby/default.section</item>
			 				<item>/global.page</item>
			 			</list>
			 		</global>
			 		<header>
			 			<list>
			 				<item>/header.page</item>
			 			</list>
			 		</header>
			 		<footer>
			 			<list>
			 				<item>/footer.page</item>
			 			</list>
			 		</footer>
			 	</includes>
			 </item>
			 <item>
			 	<name>Lincolnshire</name>
			 	<client>lincolnshire</client>
			 	<visibletag>BBC Lincolnshire</visibletag>
			 	<url>http://www.bbc.co.uk/lincolnshire/</url>
			 	<logo1>logos/logo1_lincolnshire.gif</logo1>
			 	<rsshelp>http://www.bbc.co.uk/feedfactory/help.shtml</rsshelp>
			 	<css>
			 		<list>
			 			<item>/englandcms/style/common.css</item>
						<item>/englandcms/style/include_common.css</item>
						<item>/englandcms/style/index.css</item>
						
						<!-- server specific -->
						<item>css/common.css</item>
						<item>css/styles.css</item>
						<item>css/editor.css</item>
			 		</list>
			 	</css>
			 	<includes>
			 		<global>
			 			<list>
			 				<item>/englandcms/wil/includes/lincolnshire/default.site</item>
			 				<item>/englandcms/wil/includes/lincolnshire/default.section</item>
			 				<item>/global.page</item>
			 			</list>
			 		</global>
			 		<header>
			 			<list>
			 				<item>/header.page</item>
			 			</list>
			 		</header>
			 		<footer>
			 			<list>
			 				<item>/footer.page</item>
			 			</list>
			 		</footer>
			 	</includes>
			 </item>
			 <item>
			 	<name>Isle of Man</name>
			 	<client>isleofman</client>
			 	<visibletag>BBC Isle of Man</visibletag>
			 	<url>http://www.bbc.co.uk/isleofman/</url>
			 	<logo1>logos/logo1_isleofman.gif</logo1>
			 	<rsshelp>http://www.bbc.co.uk/feedfactory/help.shtml</rsshelp>
			 	<css>
			 		<list>
			 			<item>/englandcms/style/common.css</item>
						<item>/englandcms/style/include_common.css</item>
						<item>/englandcms/style/index.css</item>
						
						<!-- server specific -->
						<item>css/common.css</item>
						<item>css/styles.css</item>
						<item>css/editor.css</item>
			 		</list>
			 	</css>
			 	<includes>
			 		<global>
			 			<list>
			 				<item>/englandcms/wil/includes/isleofman/default.site</item>
			 				<item>/englandcms/wil/includes/isleofman/default.section</item>
			 				<item>/global.page</item>
			 			</list>
			 		</global>
			 		<header>
			 			<list>
			 				<item>/header.page</item>
			 			</list>
			 		</header>
			 		<footer>
			 			<list>
			 				<item>/footer.page</item>
			 			</list>
			 		</footer>
			 	</includes>
			 </item>
			 <item>
			 	<name>Oxford</name>
			 	<client>oxford</client>
			 	<visibletag>BBC Oxford</visibletag>
			 	<url>http://www.bbc.co.uk/oxford/</url>
			 	<logo1>logos/logo1_oxford.gif</logo1>
			 	<rsshelp>http://www.bbc.co.uk/feedfactory/help.shtml</rsshelp>
			 	<css>
			 		<list>
			 			<item>/englandcms/style/common.css</item>
						<item>/englandcms/style/include_common.css</item>
						<item>/englandcms/style/index.css</item>
						
						<!-- server specific -->
						<item>css/common.css</item>
						<item>css/styles.css</item>
						<item>css/editor.css</item>
			 		</list>
			 	</css>
			 	<includes>
			 		<global>
			 			<list>
			 				<item>/englandcms/wil/includes/oxford/default.site</item>
			 				<item>/englandcms/wil/includes/oxford/default.section</item>
			 				<item>/global.page</item>
			 			</list>
			 		</global>
			 		<header>
			 			<list>
			 				<item>/header.page</item>
			 			</list>
			 		</header>
			 		<footer>
			 			<list>
			 				<item>/footer.page</item>
			 			</list>
			 		</footer>
			 	</includes>
			 </item>
			 <item>
			 	<name>Bradford &amp; West Yorkshire</name>
			 	<client>bradford</client>
			 	<visibletag>BBC Bradford &amp; West Yorkshire</visibletag>
			 	<url>http://www.bbc.co.uk/bradford/</url>
			 	<logo1>logos/logo1_bradford.gif</logo1>
			 	<rsshelp>http://www.bbc.co.uk/feedfactory/help.shtml</rsshelp>
			 	<css>
			 		<list>
			 			<item>/englandcms/style/common.css</item>
						<item>/englandcms/style/include_common.css</item>
						<item>/englandcms/style/index.css</item>
						
						<!-- server specific -->
						<item>css/common.css</item>
						<item>css/styles.css</item>
						<item>css/editor.css</item>
			 		</list>
			 	</css>
			 	<includes>
			 		<global>
			 			<list>
			 				<item>/englandcms/wil/includes/bradford/default.site</item>
			 				<item>/englandcms/wil/includes/bradford/default.section</item>
			 				<item>/global.page</item>
			 			</list>
			 		</global>
			 		<header>
			 			<list>
			 				<item>/header.page</item>
			 			</list>
			 		</header>
			 		<footer>
			 			<list>
			 				<item>/footer.page</item>
			 			</list>
			 		</footer>
			 	</includes>
			 </item>
			 <item>
			 	<name>Leeds</name>
			 	<client>leeds</client>
			 	<visibletag>BBC Leeds</visibletag>
			 	<url>http://www.bbc.co.uk/leeds/</url>
			 	<logo1>logos/logo1_leeds.gif</logo1>
			 	<rsshelp>http://www.bbc.co.uk/feedfactory/help.shtml</rsshelp>
			 	<css>
			 		<list>
			 			<item>/englandcms/style/common.css</item>
						<item>/englandcms/style/include_common.css</item>
						<item>/englandcms/style/index.css</item>
						
						<!-- server specific -->
						<item>css/common.css</item>
						<item>css/styles.css</item>
						<item>css/editor.css</item>
			 		</list>
			 	</css>
			 	<includes>
			 		<global>
			 			<list>
			 				<item>/englandcms/wil/includes/leeds/default.site</item>
			 				<item>/englandcms/wil/includes/leeds/default.section</item>
			 				<item>/global.page</item>
			 			</list>
			 		</global>
			 		<header>
			 			<list>
			 				<item>/header.page</item>
			 			</list>
			 		</header>
			 		<footer>
			 			<list>
			 				<item>/footer.page</item>
			 			</list>
			 		</footer>
			 	</includes>
			 </item>
			 <item>
			 	<name>Humber</name>
			 	<client>humber</client>
			 	<visibletag>BBC Humber</visibletag>
			 	<url>http://www.bbc.co.uk/humber/</url>
			 	<logo1>logos/logo1_humber.gif</logo1>
			 	<rsshelp>http://www.bbc.co.uk/feedfactory/help.shtml</rsshelp>
			 	<css>
			 		<list>
			 			<item>/englandcms/style/common.css</item>
						<item>/englandcms/style/include_common.css</item>
						<item>/englandcms/style/index.css</item>
						
						<!-- server specific -->
						<item>css/common.css</item>
						<item>css/styles.css</item>
						<item>css/editor.css</item>
			 		</list>
			 	</css>
			 	<includes>
			 		<global>
			 			<list>
			 				<item>/englandcms/wil/includes/humber/default.site</item>
			 				<item>/englandcms/wil/includes/humber/default.section</item>
			 				<item>/global.page</item>
			 			</list>
			 		</global>
			 		<header>
			 			<list>
			 				<item>/header.page</item>
			 			</list>
			 		</header>
			 		<footer>
			 			<list>
			 				<item>/footer.page</item>
			 			</list>
			 		</footer>
			 	</includes>
			 </item>
			 <item>
			 	<name>Radio 4 - Today</name>
			 	<client>radio4today</client>
			 	<visibletag>BBC Radio 4 - Today</visibletag>
			 	<url>http://www.bbc.co.uk/radio4/today</url>
			 	<logo1>logos/logo1_radio4today.gif</logo1>
			 	<rsshelp>http://www.bbc.co.uk/feedfactory/help.shtml</rsshelp>
			 	<css>
			 		<list>	
						<item>/radio4/today/styles/new_home.css</item>
			 			<item>/memoryshare/clients/radio4/style/common.css</item>
						<item>/memoryshare/clients/radio4/style/include_common.css</item>
						<item>/memoryshare/clients/radio4/style/index.css</item>

						<!-- server specific -->
						<item>css/common.css</item>
						<item>css/styles.css</item>
						<item>css/editor.css</item>
						
			 		</list>
			 	</css>
			 	<includes>
			 		<global>
			 			<list>
			 				<item>/radio4/today/includes/today.site</item>
			 				<item>/radio4/today/includes/today.section</item>
			 				<item>/global.page</item>
			 			</list>
			 		</global>
			 		<header>
			 			<list>
			 				<item>/header.page</item>
			 			</list>
			 		</header>
			 		<footer>
			 			<list>
			 				<item>/footer.page</item>
			 			</list>
			 		</footer>
			 	</includes>
			 </item>
			 <item>
			 	<name>Writing the Century</name>
			 	<client>radio4writingthecentury</client>
			 	<visibletag>BBC Radio 4 - Writing the Century</visibletag>
			 	<url>http://www.bbc.co.uk/radio4/arts/writing_the_century.shtml</url>
			 	<logo1>logos/logo1_writingthecentury.gif</logo1>
			 	<rsshelp>http://www.bbc.co.uk/feedfactory/help.shtml</rsshelp>
			 	<css>
			 		<list>
			 			<item>/radio4/styles/lhnav.css</item>
			 			<item>/radio4/styles/arts.css</item>
						<item>/memoryshare/clients/writingthecentury/style/common.css</item>
						<item>/memoryshare/clients/writingthecentury/style/include_common.css</item>
						<item>/memoryshare/clients/writingthecentury/style/index.css</item>
						
												
						<!-- server specific -->
						<item>css/common.css</item>
						<item>css/styles.css</item>
						<item>css/editor.css</item>
			 		</list>
			 	</css>
			 	<includes>
			 		<global>
			 			<list>
			 				<item>/radio4/includes/r4.site</item>
			 				<item>/memoryshare/clients/writingthecentury/r4.section</item>
			 				<item>/global.page</item>
			 			</list>
			 		</global>
			 		<header>
			 			<list>
			 				<item>/header.page</item>
			 			</list>
			 		</header>
			 		<footer>
			 			<list>
			 				<item>/footer.page</item>
			 			</list>
			 		</footer>
			 	</includes>
			 </item>
			 <item>
			 	<name>1968</name>
			 	<client>radio4_1968</client>
			 	<visibletag>BBC Radio 4 - 1968</visibletag>
			 	<url>http://www.bbc.co.uk/radio4/</url>
			 	<logo1>logos/logo1_radio4_1968.gif</logo1>
			 	<rsshelp>http://www.bbc.co.uk/feedfactory/help.shtml</rsshelp>
			 	<css>
			 		<list>
			 			<item>/radio4/styles/lhnav.css</item>
			 			<item>/radio4/styles/arts.css</item>
						<item>/memoryshare/clients/radio4_1968/style/common.css</item>
						<item>/memoryshare/clients/radio4_1968/style/include_common.css</item>
						<item>/memoryshare/clients/radio4_1968/style/index.css</item>
						
												
						<!-- server specific -->
						<item>css/common.css</item>
						<item>css/styles.css</item>
						<item>css/editor.css</item>
			 		</list>
			 	</css>
			 	<includes>
			 		<global>
			 			<list>
			 				<item>/radio4/includes/r4.site</item>
			 				<item>/memoryshare/clients/radio4_1968/radio4_1968.section</item>
			 				<item>/global.page</item>
			 			</list>
			 		</global>
			 		<header>
			 			<list>
			 				<item>/header.page</item>
			 			</list>
			 		</header>
			 		<footer>
			 			<list>
			 				<item>/footer.page</item>
			 			</list>
			 		</footer>
			 	</includes>
			 </item>
			 <item>
			 	<name>Radio 4 - Saturday Live</name>
			 	<client>radio4_saturdaylive</client>
			 	<visibletag>Radio 4 - Saturday Live</visibletag>
			 	<url>http://www.bbc.co.uk/radio4/saturdaylive/saturdaylive.shtml</url>
			 	<logo1>logos/logo1_radio4_saturdaylive.gif</logo1>
			 	<rsshelp>http://www.bbc.co.uk/feedfactory/help.shtml</rsshelp>
			 	<css>
			 		<list>
			 			<item>/memoryshare/clients/radio4_saturdaylive/style/common.css</item>
						<item>/memoryshare/clients/radio4_saturdaylive/style/include_common.css</item>
						<item>/memoryshare/clients/radio4_saturdaylive/style/index.css</item>
						
						<!-- server specific -->
						<item>css/common.css</item>
						<item>css/styles.css</item>
						<item>css/editor.css</item>
						<item>css/calendar.css</item>
			 		</list>
			 	</css>
			 	<includes>
			 		<global>
			 			<list>
			 				<item>/memoryshare/clients/radio4_saturdaylive/default.site</item>
			 				<item>/memoryshare/clients/radio4_saturdaylive/default.section</item>
			 				<item>/global.page</item>
			 			</list>
			 		</global>
			 		<header>
			 			<list>
			 				<item>/header.page</item>
			 			</list>
			 		</header>
			 		<footer>
			 			<list>
			 				<item>/footer.page</item>
			 			</list>
			 		</footer>
			 	</includes>
			 </item>
			 <item>
			 	<name>Writing the Century</name>
			 	<client>writingthecentury</client>
			 	<visibletag>BBC Radio 4 - Writing the Century</visibletag>
			 	<url>http://www.bbc.co.uk/radio4/arts/writing_the_century.shtml</url>
			 	<logo1>logos/logo1_writingthecentury.gif</logo1>
			 	<rsshelp>http://www.bbc.co.uk/feedfactory/help.shtml</rsshelp>
			 	<css>
			 		<list>
			 			<item>/radio4/styles/lhnav.css</item>
			 			<item>/radio4/styles/arts.css</item>
						<item>/memoryshare/clients/writingthecentury/style/common.css</item>
						<item>/memoryshare/clients/writingthecentury/style/include_common.css</item>
						<item>/memoryshare/clients/writingthecentury/style/index.css</item>
						
												
						<!-- server specific -->
						<item>css/common.css</item>
						<item>css/styles.css</item>
						<item>css/editor.css</item>
			 		</list>
			 	</css>
			 	<includes>
			 		<global>
			 			<list>
			 				<item>/radio4/includes/r4.site</item>
			 				<item>/memoryshare/clients/writingthecentury/r4.section</item>
			 				<item>/global.page</item>
			 			</list>
			 		</global>
			 		<header>
			 			<list>
			 				<item>/header.page</item>
			 			</list>
			 		</header>
			 		<footer>
			 			<list>
			 				<item>/footer.page</item>
			 			</list>
			 		</footer>
			 	</includes>
			 </item>
			 <item>
			 	<name>World Service</name>
			 	<client>worldservice</client>
			 	<visibletag>BBC World Service - Free to Speak</visibletag>
			 	<url>http://www.bbc.co.uk/worldservice/</url>
			 	<logo1>logos/logo1_worldservice.gif</logo1>
			 	<rsshelp>http://www.bbc.co.uk/feedfactory/help.shtml</rsshelp>
			 	<css>
			 		<list>
			 			<item>/memoryshare/clients/worldservice/style/common.css</item>
						<item>/memoryshare/clients/worldservice/style/include_common.css</item>
						<item>/memoryshare/clients/worldservice/style/index.css</item>
						
						<!-- server specific -->
						<item>css/common.css</item>
						<item>css/styles.css</item>
						<item>css/editor.css</item>
						<item>css/calendar.css</item>
			 		</list>
			 	</css>
			 	<includes>
			 		<global>
			 			<list>
			 				<item>/memoryshare/clients/worldservice/default.site</item>
			 				<item>/memoryshare/clients/worldservice/default.section</item>
			 				<item>/global.page</item>
			 			</list>
			 		</global>
			 		<header>
			 			<list>
			 				<item>/header.page</item>
			 			</list>
			 		</header>
			 		<footer>
			 			<list>
			 				<item>/footer.page</item>
			 			</list>
			 		</footer>
			 	</includes>
			 </item>
			<item>
			 	<name>Radio 1</name>
			 	<client>radio1</client>
			 	<visibletag>BBC Radio 1</visibletag>
			 	<url>http://www.bbc.co.uk/radio1/</url>
			 	<logo1>logos/logo1_radio1.gif</logo1>
			 	<rsshelp>http://www.bbc.co.uk/feedfactory/help.shtml</rsshelp>
			 	<css>
			 		<list>
						<item>/radio1/css/homepage/default.css</item>
						<item>/radio1/css/homepage/colourdefaultpopup.css</item>
						<item>/radio1/css/homepage/ie.css</item>
			 			<item>/memoryshare/clients/radio1/style/common.css</item>
						<item>/memoryshare/clients/radio1/style/include_common.css</item>
						<item>/memoryshare/clients/radio1/style/index.css</item>
						
						<!-- server specific -->
						<item>css/common.css</item>
						<item>css/styles.css</item>
						<item>css/editor.css</item>
			 		</list>
			 	</css>
			 	<includes>
			 		<global>
			 			<list>
			 				<item>/radio1/includes/radio1.site</item>
			 				<item>/radio1/includes/radio1.section</item>
			 				<item>/global.page</item>
			 			</list>
			 		</global>
			 		<header>
			 			<list>
			 				<item>/header.page</item>
			 			</list>
			 		</header>
			 		<footer>
			 			<list>
			 				<item>/footer.page</item>
			 			</list>
			 		</footer>
			 	</includes>
			 </item>
			 <item>
			 	<name>BBC Memories</name>
			 	<client>bbcmemories</client>
			 	<visibletag>BBC Memories</visibletag>
			 	<url>http://www.bbc.co.uk/heritage/bbcmemories/</url>
			 	<logo1>logos/logo1_bbcmemories.gif</logo1>
			 	<rsshelp>http://www.bbc.co.uk/feedfactory/help.shtml</rsshelp>
			 	<css>
			 		<list>
						<item>/heritage/bbcmemories/includes/memshare.css</item>
						
						<!-- server specific -->
						<item>css/common.css</item>
						<item>css/styles.css</item>
						<item>css/editor.css</item>
			 		</list>
			 	</css>
			 	<includes>
			 		<global>
			 			<list>
			 				<item>/heritage/bbcmemories/includes/memshare.site</item>
			 				<item>/heritage/bbcmemories/includes/memshare.section</item>
			 				<item>/global.page</item>
			 			</list>
			 		</global>
			 		<header>
			 			<list>
			 				<item>/header.page</item>
			 			</list>
			 		</header>
			 		<footer>
			 			<list>
			 				<item>/footer.page</item>
			 			</list>
			 		</footer>
			 	</includes>
			 </item>
			  <item>
			 	<name>Pop on Trial</name>
			 	<client>popontrial</client>
			 	<visibletag>BBC Pop on Trial</visibletag>
			 	<url>http://www.bbc.co.uk/musictv/popontrial/</url>
			 	<logo1>logos/logo1_popontrial.gif</logo1>
			 	<rsshelp>http://www.bbc.co.uk/feedfactory/help.shtml</rsshelp>
			 	<css>
			 		<list>
						<item>/musictv/popontrial/includes/css/memshare.css</item>
						
						<!-- server specific -->
						<item>css/common.css</item>
						<item>css/styles.css</item>
						<item>css/editor.css</item>
			 		</list>
			 	</css>
			 	<includes>
			 		<global>
			 			<list>
			 				<item>/musictv/popontrial/includes/barley/pot.site</item>
			 				<item>/musictv/popontrial/includes/barley/pot.section</item>
			 				<item>/global.page</item>
			 			</list>
			 		</global>
			 		<header>
			 			<list>
			 				<item>/header.page</item>
			 			</list>
			 		</header>
			 		<footer>
			 			<list>
			 				<item>/footer.page</item>
			 			</list>
			 		</footer>
			 	</includes>
			 </item>
			 <item>
			 	<name>Wales</name>
			 	<client>wales</client>
			 	<visibletag>BBC Wales</visibletag>
			 	<url>http://www.bbc.co.uk/wales/</url>
			 	<logo1>logos/logo1_wales.gif</logo1>
			 	<rsshelp>http://www.bbc.co.uk/feedfactory/help.shtml</rsshelp>
			 	<css>
			 		<list>
			 			<item>/memoryshare/clients/memoryshare/style/common.css</item>
						<item>/memoryshare/clients/memoryshare/style/include_common.css</item>
						<item>/memoryshare/clients/memoryshare/style/index.css</item>
						
						<!-- server specific -->
						<item>css/common.css</item>
						<item>css/styles.css</item>
						<item>css/editor.css</item>
						<item>css/calendar.css</item>
			 		</list>
			 	</css>
			 	<includes>
			 		<global>
			 			<list>
			 				<item>/memoryshare/clients/memoryshare/default.site</item>
			 				<item>/memoryshare/clients/memoryshare/default.section</item>
			 				<item>/global.page</item>
			 			</list>
			 		</global>
			 		<header>
			 			<list>
			 				<item>/header.page</item>
			 			</list>
			 		</header>
			 		<footer>
			 			<list>
			 				<item>/footer.page</item>
			 			</list>
			 		</footer>
			 	</includes>
			 </item>
			 <item>
			 	<name>Timescapes</name>
			 	<client>timescapes</client>
			 	<visibletag>Timescapes</visibletag>
			 	<url>http://www.bbc.co.uk/worldservice/</url>
			 	<logo1>logos/logo1_timescapes.gif</logo1>
			 	<rsshelp>http://www.bbc.co.uk/feedfactory/help.shtml</rsshelp>
			 	<css>
			 		<list>
			 			<item>/memoryshare/clients/timescapes/style/common.css</item>
						<item>/memoryshare/clients/timescapes/style/include_common.css</item>
						<item>/memoryshare/clients/timescapes/style/index.css</item>
						
						<!-- server specific -->
						<item>css/common.css</item>
						<item>css/styles.css</item>
						<item>css/editor.css</item>
						<item>css/calendar.css</item>
			 		</list>
			 	</css>
			 	<includes>
			 		<global>
			 			<list>
			 				<item>/memoryshare/clients/timescapes/default.site</item>
			 				<item>/memoryshare/clients/timescapes/default.section</item>
			 				<item>/global.page</item>
			 			</list>
			 		</global>
			 		<header>
			 			<list>
			 				<item>/header.page</item>
			 			</list>
			 		</header>
			 		<footer>
			 			<list>
			 				<item>/footer.page</item>
			 			</list>
			 		</footer>
			 	</includes>
			 </item>
			 <item>
			 	<name>LSBU Sisters and Brothers</name>
			 	<client>lsbu_sistersandbrothers</client>
			 	<visibletag>LSBU Sisters and Brothers</visibletag>
			 	<url>http://www.lsbu.ac.uk/families/brothersandsisters/</url>
			 	<logo1>logos/logo1_lsbu_sistersandbrothers.gif</logo1>
			 	<rsshelp>http://www.bbc.co.uk/feedfactory/help.shtml</rsshelp>
			 	<css>
			 		<list>
			 			<item>/memoryshare/clients/lsbu_sistersandbrothers/style/common.css</item>
						<item>/memoryshare/clients/lsbu_sistersandbrothers/style/include_common.css</item>
						<item>/memoryshare/clients/lsbu_sistersandbrothers/style/index.css</item>
						
						<!-- server specific -->
						<item>css/common.css</item>
						<item>css/styles.css</item>
						<item>css/editor.css</item>
						<item>css/calendar.css</item>
			 		</list>
			 	</css>
			 	<includes>
			 		<global>
			 			<list>
			 				<item>/memoryshare/clients/lsbu_sistersandbrothers/default.site</item>
			 				<item>/memoryshare/clients/lsbu_sistersandbrothers/default.section</item>
			 				<item>/global.page</item>
			 			</list>
			 		</global>
			 		<header>
			 			<list>
			 				<item>/header.page</item>
			 			</list>
			 		</header>
			 		<footer>
			 			<list>
			 				<item>/footer.page</item>
			 			</list>
			 		</footer>
			 	</includes>
			 </item>
			 <item>
			 	<name>Radio 2 Life2live 70, Not Out!</name>
			 	<client>life2live</client>
			 	<visibletag>Radio 2 Life2live 70, Not Out!</visibletag>
			 	<url>http://www.bbc.co.uk/radio2/life2live/</url>
			 	<logo1>logos/logo1_life2live.gif</logo1>
			 	<rsshelp>http://www.bbc.co.uk/feedfactory/help.shtml</rsshelp>
			 	<css>
			 		<list>
						<item>/memoryshare/clients/life2live/style/common.css</item>
						<item>/memoryshare/clients/life2live/style/include_common.css</item>
						<item>/memoryshare/clients/life2live/style/index.css</item>
						
						<item>/radio2/rebrand.css</item>
						<item>/radio2/events/events.css</item>
						
			 			
						
						<!-- server specific -->
						<item>css/common.css</item>
						<item>css/styles.css</item>
						<item>css/editor.css</item>
						<item>css/calendar.css</item>
			 		</list>
			 	</css>
			 	<includes>
			 		<global>
			 			<list>
			 				<item>/radio2/includes/radio2.site</item>
			 				<item>/radio2/includes/radio2.section</item>
			 				<item>/global.page</item>
			 			</list>
			 		</global>
			 		<header>
			 			<list>
			 				<item>/header.page</item>
			 			</list>
			 		</header>
			 		<footer>
			 			<list>
			 				<item>/footer.page</item>
			 			</list>
			 		</footer>
			 	</includes>
			 </item>
			<item>
			 	<name>MLA - The People's Record</name>
			 	<client>peoplesrecord</client>
			 	<visibletag>MLA - The People's Record</visibletag>
			 	<url>http://www.mla.gov.uk/programmes/settingthepace/Peoples_Record</url>
			 	<logo1>logos/logo1_peoplesrecord.gif</logo1>
			 	<rsshelp>http://www.bbc.co.uk/feedfactory/help.shtml</rsshelp>
			 	<css>
			 		<list>
			 			<item>/memoryshare/clients/memoryshare/style/common.css</item>
						<item>/memoryshare/clients/memoryshare/style/include_common.css</item>
						<item>/memoryshare/clients/memoryshare/style/index.css</item>
						
						<!-- server specific -->
						<item>css/common.css</item>
						<item>css/styles.css</item>
						<item>css/editor.css</item>
						<item>css/calendar.css</item>
			 		</list>
			 	</css>
			 	<includes>
			 		<global>
			 			<list>
			 				<item>/memoryshare/clients/memoryshare/default.site</item>
			 				<item>/memoryshare/clients/memoryshare/default.section</item>
			 				<item>/global.page</item>
			 			</list>
			 		</global>
			 		<header>
			 			<list>
			 				<item>/header.page</item>
			 			</list>
			 		</header>
			 		<footer>
			 			<list>
			 				<item>/footer.page</item>
			 			</list>
			 		</footer>
			 	</includes>
			 </item>
			 <item>
			 	<name>testsite</name>
			 	<client>testsite</client>
			 	<visibletag>testsite</visibletag>
			 	<url>http://www.bbc.co.uk/</url>
			 	<logo1>logos/logo1.gif</logo1>
			 	<rsshelp>http://www.bbc.co.uk/feedfactory/help.shtml</rsshelp>
			 	<css>
			 		<list>
			 			<item>/memoryshare/clients/testsite/style/common.css</item>
						<item>/memoryshare/clients/testsite/style/include_common.css</item>
						<item>/memoryshare/clients/testsite/style/index.css</item>
						
						<!-- server specific -->
						<item>css/common.css</item>
						<item>css/styles.css</item>
						<item>css/editor.css</item>
						<item>css/calendar.css</item>
			 		</list>
			 	</css>
			 	<includes>
			 		<global>
			 			<list>
			 				<item>/memoryshare/clients/testsite/default.site</item>
			 				<item>/memoryshare/clients/testsite/default.section</item>
			 				<item>/global.page</item>
			 			</list>
			 		</global>
			 		<header>
			 			<list>
			 				<item>/header.page</item>
			 			</list>
			 		</header>
			 		<footer>
			 			<list>
			 				<item>/footer.page</item>
			 			</list>
			 		</footer>
			 	</includes>
			 </item>
			 <item>
			 	<name>Radio 4 - Man on the Moon</name>
			 	<client>radio4manonthemoon</client>
			 	<visibletag>Radio 4 - Man on the Moon</visibletag>
			 	<url>http://www.bbc.co.uk/radio4/</url>
			 	<logo1>logos/logo1_memoryshare.gif</logo1>
			 	<rsshelp>http://www.bbc.co.uk/feedfactory/help.shtml</rsshelp>
			 	<css>
			 		<list>
			 			<item>/memoryshare/clients/memoryshare/style/common.css</item>
						<item>/memoryshare/clients/memoryshare/style/include_common.css</item>
						<item>/memoryshare/clients/memoryshare/style/index.css</item>
						
						<!-- server specific -->
						<item>css/common.css</item>
						<item>css/styles.css</item>
						<item>css/editor.css</item>
						<item>css/calendar.css</item>
			 		</list>
			 	</css>
			 	<includes>
			 		<global>
			 			<list>
			 				<item>/memoryshare/clients/memoryshare/default.site</item>
			 				<item>/memoryshare/clients/memoryshare/default.section</item>
			 				<item>/global.page</item>
			 			</list>
			 		</global>
			 		<header>
			 			<list>
			 				<item>/header.page</item>
			 			</list>
			 		</header>
			 		<footer>
			 			<list>
			 				<item>/footer.page</item>
			 			</list>
			 		</footer>
			 	</includes>
			 </item>
			<item>
			 	<name>Memoryshare</name>
			 	<client>memoryshare</client>
			 	<visibletag>BBC Memoryshare</visibletag>
			 	<url>http://www.bbc.co.uk/memoryshare/</url>
			 	<logo1>logos/logo1_memoryshare.gif</logo1>
			 	<rsshelp>http://www.bbc.co.uk/feedfactory/help.shtml</rsshelp>
			 	<css>
			 		<list>
			 			<item>/memoryshare/clients/memoryshare/style/common.css</item>
						<item>/memoryshare/clients/memoryshare/style/include_common.css</item>
						<item>/memoryshare/clients/memoryshare/style/index.css</item>
						
						<!-- server specific -->
						<item>css/common.css</item>
						<item>css/styles.css</item>
						<item>css/editor.css</item>
						<item>css/calendar.css</item>
			 		</list>
			 	</css>
			 	<includes>
			 		<global>
			 			<list>
			 				<item>/memoryshare/clients/memoryshare/default.site</item>
			 				<item>/memoryshare/clients/memoryshare/default.section</item>
			 				<item>/global.page</item>
			 			</list>
			 		</global>
			 		<header>
			 			<list>
			 				<item>/header.page</item>
			 			</list>
			 		</header>
			 		<footer>
			 			<list>
			 				<item>/footer.page</item>
			 			</list>
			 		</footer>
			 	</includes>
			 </item>
			<item>
			 	<name>BBC</name>
			 	<client>england</client>
			 	<visibletag>BBC England</visibletag>
			 	<url>http://www.bbc.co.uk/</url>
			 	<logo1>logos/logo1_england.gif</logo1>
			 	<rsshelp>http://www.bbc.co.uk/feedfactory/help.shtml</rsshelp>
			 	<css>
			 		<list>
			 			<item>/englandcms/style/common.css</item>
						<item>/englandcms/style/include_common.css</item>
						<item>/englandcms/style/index.css</item>
						
						<!-- server specific -->
						<item>css/common.css</item>
						<item>css/styles.css</item>
						<item>css/editor.css</item>
			 		</list>
			 	</css>
			 	<includes>
			 		<global>
			 			<list>
			 				<item>/englandcms/includes/england/default.site</item>
			 				<item>/englandcms/includes/england/default.section</item>
			 				<item>/global.page</item>
			 			</list>
			 		</global>
			 		<header>
			 			<list>
			 				<item>/header.page</item>
			 			</list>
			 		</header>
			 		<footer>
			 			<list>
			 				<item>/footer.page</item>
			 			</list>
			 		</footer>
			 	</includes>
			</item>
		</list>
	</xsl:variable>
</xsl:stylesheet>
