<!DOCTYPE xsl:stylesheet [
	<!ENTITY nbsp "&#160;">
]>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:msxsl="urn:schemas-microsoft-com:xslt" xmlns:local="#local-functions" xmlns:s="urn:schemas-microsoft-com:xml-data" xmlns:dt="urn:schemas-microsoft-com:datatypes" exclude-result-prefixes="msxsl local s dt">
	
<xsl:variable name="user_intro_fields">
	<![CDATA[<MULTI-INPUT>
		<REQUIRED NAME='TYPE'></REQUIRED>
		<REQUIRED NAME='BODY'><VALIDATE TYPE='EMPTY'/></REQUIRED>
		<REQUIRED NAME='TITLE'></REQUIRED>
		<ELEMENT NAME='SPORTINGINTEREST1'><VALIDATE TYPE='EMPTY'/></ELEMENT>
		<ELEMENT NAME='SPORTINGINTEREST2'></ELEMENT>
		<ELEMENT NAME='SPORTINGINTEREST3'></ELEMENT>
		<ELEMENT NAME='FAVOURITEPLAYER'><VALIDATE TYPE='EMPTY'/></ELEMENT>
		<ELEMENT NAME='TEAMPLAYEDIN'></ELEMENT>
		<ELEMENT NAME='TEAMPLAYEDINLINK'></ELEMENT>
		<ELEMENT NAME='FAVOURITEMATCH'><VALIDATE TYPE='EMPTY'/></ELEMENT>
		<ELEMENT NAME='FAVOURITEMATCHLINK'></ELEMENT>
		<ELEMENT NAME='EXTERNALLINK1'></ELEMENT>
		<ELEMENT NAME='EXTERNALLINK1TITLE'></ELEMENT>
		<ELEMENT NAME='EXTERNALLINK2'></ELEMENT>
		<ELEMENT NAME='EXTERNALLINK2TITLE'></ELEMENT>
		<ELEMENT NAME='EXTERNALLINK3'></ELEMENT>
		<ELEMENT NAME='EXTERNALLINK3TITLE'></ELEMENT>
		
		<ELEMENT NAME='DATECREATED' EI='add'></ELEMENT>
		<ELEMENT NAME='LASTUPDATED' EI='add'></ELEMENT>
		<ELEMENT NAME='AUTHORNAME' EI='add'></ELEMENT>
		<ELEMENT NAME='AUTHORUSERID' EI='add'></ELEMENT>
		<ELEMENT NAME='AUTHORUSERNAME' EI='add'></ELEMENT>
		
		<ELEMENT NAME='TYPEOFARTICLE' ACTION='KEYPHRASE'></ELEMENT>
	</MULTI-INPUT>]]>
</xsl:variable>

<xsl:variable name="article_form">
	<![CDATA[<MULTI-INPUT>
		<REQUIRED NAME='TYPE'></REQUIRED>
		<REQUIRED NAME='BODY'><VALIDATE TYPE='EMPTY'/></REQUIRED>
		<REQUIRED NAME='TITLE'><VALIDATE TYPE='EMPTY'/></REQUIRED>
		
		<ELEMENT NAME='IMAGE'></ELEMENT>
    <ELEMENT NAME='EMPURL'></ELEMENT>
    <ELEMENT NAME='YOUTUBEURL'></ELEMENT>
		
		<ELEMENT NAME='ARTICLELINK'></ELEMENT>
		<ELEMENT NAME='ARTICLELINKTITLE'></ELEMENT>
		<ELEMENT NAME='ARTICLEFORUMSTYLE'></ELEMENT>
		<ELEMENT NAME='POLLTYPE1'></ELEMENT>
		
		<ELEMENT NAME='DATECREATED' EI='add'></ELEMENT>
		<ELEMENT NAME='LASTUPDATED' EI='add'></ELEMENT>
		<ELEMENT NAME='AUTHORNAME' EI='add'></ELEMENT>
		<ELEMENT NAME='AUTHORUSERID' EI='add'></ELEMENT>
		<ELEMENT NAME='AUTHORUSERNAME' EI='add'></ELEMENT>
		
		<ELEMENT NAME='TYPEOFARTICLE' EI='add' ACTION='KEYPHRASE'></ELEMENT>
		<ELEMENT NAME='SPORT' EI='add' ACTION='KEYPHRASE'><VALIDATE TYPE='EMPTY'/></ELEMENT>
		<ELEMENT NAME='OTHERSPORT' EI='add'  ACTION='KEYPHRASE'></ELEMENT>
		<ELEMENT NAME='OTHERSPORTUSERS' EI='add'  ACTION='KEYPHRASE'></ELEMENT>
		<ELEMENT NAME='COMPETITION' EI='add' ACTION='KEYPHRASE'></ELEMENT>
		<ELEMENT NAME='OTHERCOMPETITION' EI='add'  ACTION='KEYPHRASE'></ELEMENT>
		<ELEMENT NAME='TEAM' EI='add' ACTION='KEYPHRASE'></ELEMENT>
		<ELEMENT NAME='OTHERTEAM' EI='add'  ACTION='KEYPHRASE'></ELEMENT>
		
		<ELEMENT NAME='MANAGERSPICK' EI='add' ACTION='KEYPHRASE'></ELEMENT>
		
		<ELEMENT NAME='AUTOCOMPETITIONS' ACTION='KEYPHRASE'></ELEMENT>
		<ELEMENT NAME='AUTONAMES' ACTION='KEYPHRASE'></ELEMENT>
	</MULTI-INPUT>]]>
	
</xsl:variable>


<xsl:variable name="match_report_form">
	<![CDATA[<MULTI-INPUT>
		<REQUIRED NAME='TYPE'></REQUIRED>
		<REQUIRED NAME='BODY'><VALIDATE TYPE='EMPTY'/></REQUIRED>
		<REQUIRED NAME='TITLE'><VALIDATE TYPE='EMPTY'/></REQUIRED>
		
		<ELEMENT NAME='HOMETEAM' EI='add' ACTION='KEYPHRASE'><VALIDATE TYPE='EMPTY'/></ELEMENT>
		<ELEMENT NAME='HOMETEAMOTHER' EI='add' ACTION='KEYPHRASE'></ELEMENT>
		<ELEMENT NAME='HOMETEAMSCORE' EI='add'></ELEMENT>
		<ELEMENT NAME='AWAYTEAM'  EI='add' ACTION='KEYPHRASE'><VALIDATE TYPE='EMPTY'/></ELEMENT>
		<ELEMENT NAME='AWAYTEAMOTHER' EI='add' ACTION='KEYPHRASE'></ELEMENT>
		<ELEMENT NAME='AWAYTEAMSCORE'  EI='add'></ELEMENT>
		<ELEMENT NAME='DATEDAY'  EI='add' ACTION='KEYPHRASE'><VALIDATE TYPE='EMPTY'/></ELEMENT>
		<ELEMENT NAME='DATEMONTH'  EI='add' ACTION='KEYPHRASE'><VALIDATE TYPE='EMPTY'/></ELEMENT>
		<ELEMENT NAME='DATEYEAR'  EI='add' ACTION='KEYPHRASE'><VALIDATE TYPE='EMPTY'/></ELEMENT>
		<ELEMENT NAME='VENUE' ACTION='KEYPHRASE'></ELEMENT>
		<ELEMENT NAME='ATTENDANCE'></ELEMENT>
		<ELEMENT NAME='PLAYEROFTHEMATCH' ACTION='KEYPHRASE'></ELEMENT>
		<ELEMENT NAME='TEAMLIST'></ELEMENT>
		<ELEMENT NAME='ARTICLELINK'></ELEMENT>
		<ELEMENT NAME='ARTICLELINKTITLE'></ELEMENT>
		<ELEMENT NAME='ARTICLEFORUMSTYLE'></ELEMENT>
		<ELEMENT NAME='POLLTYPE1'></ELEMENT>
					
		<ELEMENT NAME='DATECREATED' EI='add'></ELEMENT>
		<ELEMENT NAME='LASTUPDATED' EI='add'></ELEMENT>
		<ELEMENT NAME='AUTHORNAME' EI='add'></ELEMENT>
		<ELEMENT NAME='AUTHORUSERID' EI='add'></ELEMENT>
		<ELEMENT NAME='AUTHORUSERNAME' EI='add'></ELEMENT>
		
		<ELEMENT NAME='TYPEOFARTICLE' EI='add' ACTION='KEYPHRASE'></ELEMENT>
		<ELEMENT NAME='SPORT' EI='add' ACTION='KEYPHRASE'><VALIDATE TYPE='EMPTY'/></ELEMENT>
		<ELEMENT NAME='OTHERSPORT' EI='add'  ACTION='KEYPHRASE'></ELEMENT>
		<ELEMENT NAME='OTHERSPORTUSERS' EI='add'  ACTION='KEYPHRASE'></ELEMENT>
		<ELEMENT NAME='COMPETITION' EI='add' ACTION='KEYPHRASE'><VALIDATE TYPE='EMPTY'/></ELEMENT>
		<ELEMENT NAME='OTHERCOMPETITION' EI='add'  ACTION='KEYPHRASE'></ELEMENT>
		<ELEMENT NAME='MANAGERSPICK' EI='add' ACTION='KEYPHRASE'></ELEMENT>
		
		<ELEMENT NAME='AUTOCOMPETITIONS' ACTION='KEYPHRASE'></ELEMENT>
		<ELEMENT NAME='AUTONAMES' ACTION='KEYPHRASE'></ELEMENT>
	</MULTI-INPUT>]]>
</xsl:variable>

<xsl:variable name="event_report_form">
	<![CDATA[<MULTI-INPUT>
		<REQUIRED NAME='TYPE'></REQUIRED>
		<REQUIRED NAME='BODY'><VALIDATE TYPE='EMPTY'/></REQUIRED>
		<REQUIRED NAME='TITLE'><VALIDATE TYPE='EMPTY'/></REQUIRED>
		
		<ELEMENT NAME='DATEDAY' ACTION='KEYPHRASE'><VALIDATE TYPE='EMPTY'/></ELEMENT>
		<ELEMENT NAME='DATEMONTH' ACTION='KEYPHRASE'><VALIDATE TYPE='EMPTY'/></ELEMENT>
		<ELEMENT NAME='DATEYEAR' ACTION='KEYPHRASE'><VALIDATE TYPE='EMPTY'/></ELEMENT>
		<ELEMENT NAME='VENUE' ACTION='KEYPHRASE'></ELEMENT>
		<ELEMENT NAME='ATTENDANCE'></ELEMENT>
		<ELEMENT NAME='STAROFTHESHOW' ACTION='KEYPHRASE'></ELEMENT>
		<ELEMENT NAME='ARTICLELINK'></ELEMENT>
		<ELEMENT NAME='ARTICLELINKTITLE'></ELEMENT>
		<ELEMENT NAME='ARTICLEFORUMSTYLE'></ELEMENT>
		<ELEMENT NAME='POLLTYPE1'></ELEMENT>
					
		<ELEMENT NAME='DATECREATED' EI='add'></ELEMENT>
		<ELEMENT NAME='LASTUPDATED' EI='add'></ELEMENT>
		<ELEMENT NAME='AUTHORNAME' EI='add'></ELEMENT>
		<ELEMENT NAME='AUTHORUSERID' EI='add'></ELEMENT>
		<ELEMENT NAME='AUTHORUSERNAME' EI='add'></ELEMENT>
		
		<ELEMENT NAME='TYPEOFARTICLE' EI='add' ACTION='KEYPHRASE'></ELEMENT>
		<ELEMENT NAME='SPORT' EI='add' ACTION='KEYPHRASE'><VALIDATE TYPE='EMPTY'/></ELEMENT>
		<ELEMENT NAME='OTHERSPORT' EI='add'  ACTION='KEYPHRASE'></ELEMENT>
		<ELEMENT NAME='OTHERSPORTUSERS' EI='add'  ACTION='KEYPHRASE'></ELEMENT>
		<ELEMENT NAME='COMPETITION' EI='add' ACTION='KEYPHRASE'><VALIDATE TYPE='EMPTY'/></ELEMENT>
		<ELEMENT NAME='OTHERCOMPETITION' EI='add'  ACTION='KEYPHRASE'></ELEMENT>
		<ELEMENT NAME='TEAM' EI='add' ACTION='KEYPHRASE'></ELEMENT>
		<ELEMENT NAME='OTHERTEAM' EI='add'  ACTION='KEYPHRASE'></ELEMENT>
		<ELEMENT NAME='MANAGERSPICK' EI='add' ACTION='KEYPHRASE'></ELEMENT>
		
		<ELEMENT NAME='COMPETITOR1' ACTION='KEYPHRASE'></ELEMENT>
		<ELEMENT NAME='COMPETITOR2' ACTION='KEYPHRASE'></ELEMENT>
		
		<ELEMENT NAME='AUTOCOMPETITIONS' ACTION='KEYPHRASE'></ELEMENT>
		<ELEMENT NAME='AUTONAMES' ACTION='KEYPHRASE'></ELEMENT>
	</MULTI-INPUT>]]>
</xsl:variable>

<xsl:variable name="player_profile_form">
	<![CDATA[<MULTI-INPUT>
		<REQUIRED NAME='TYPE'></REQUIRED>
		<REQUIRED NAME='BODY'><VALIDATE TYPE='EMPTY'/></REQUIRED>
		<REQUIRED NAME='TITLE'><VALIDATE TYPE='EMPTY'/></REQUIRED>
		
		<ELEMENT NAME='PLAYERDOB'></ELEMENT>
		<ELEMENT NAME='CURRENTTEAM' ACTION='KEYPHRASE'></ELEMENT>
		<ELEMENT NAME='OTHERCURRENTTEAM' ACTION='KEYPHRASE'></ELEMENT>
		
		
		<ELEMENT NAME='ARTICLELINK'></ELEMENT>
		<ELEMENT NAME='ARTICLELINKTITLE'></ELEMENT>
		<ELEMENT NAME='ARTICLEFORUMSTYLE'></ELEMENT>
		<ELEMENT NAME='POLLTYPE1'></ELEMENT>
					
		<ELEMENT NAME='DATECREATED' EI='add'></ELEMENT>
		<ELEMENT NAME='LASTUPDATED' EI='add'></ELEMENT>
		<ELEMENT NAME='AUTHORNAME' EI='add'></ELEMENT>
		<ELEMENT NAME='AUTHORUSERID' EI='add'></ELEMENT>
		<ELEMENT NAME='AUTHORUSERNAME' EI='add'></ELEMENT>
		
		<ELEMENT NAME='TYPEOFARTICLE' EI='add' ACTION='KEYPHRASE'></ELEMENT>
		<ELEMENT NAME='SPORT' EI='add' ACTION='KEYPHRASE'><VALIDATE TYPE='EMPTY'/></ELEMENT>
		<ELEMENT NAME='OTHERSPORT' EI='add'  ACTION='KEYPHRASE'></ELEMENT>
		<ELEMENT NAME='OTHERSPORTUSERS' EI='add'  ACTION='KEYPHRASE'></ELEMENT>
		<ELEMENT NAME='COMPETITION' EI='add' ACTION='KEYPHRASE'></ELEMENT>
		<ELEMENT NAME='OTHERCOMPETITION' EI='add'  ACTION='KEYPHRASE'></ELEMENT>
		<ELEMENT NAME='TEAM' EI='add' ACTION='KEYPHRASE'></ELEMENT>
		<ELEMENT NAME='OTHERTEAM' EI='add'  ACTION='KEYPHRASE'></ELEMENT>
		<ELEMENT NAME='MANAGERSPICK' EI='add' ACTION='KEYPHRASE'></ELEMENT>
		
		<ELEMENT NAME='AUTOCOMPETITIONS' ACTION='KEYPHRASE'></ELEMENT>
		<ELEMENT NAME='AUTONAMES' ACTION='KEYPHRASE'></ELEMENT>
	</MULTI-INPUT>]]>
</xsl:variable>


<xsl:variable name="team_profile_form">
	<![CDATA[<MULTI-INPUT>
		<REQUIRED NAME='TYPE'></REQUIRED>
		<REQUIRED NAME='BODY'><VALIDATE TYPE='EMPTY'/></REQUIRED>
		<REQUIRED NAME='TITLE'></REQUIRED>
		
		<ELEMENT NAME='HOMEVENUE'></ELEMENT>
		<ELEMENT NAME='MANAGERCOACH'></ELEMENT>
		<ELEMENT NAME='HONOURS'><VALIDATE TYPE='EMPTY'/></ELEMENT>
		
		<ELEMENT NAME='ARTICLELINK'></ELEMENT>
		<ELEMENT NAME='ARTICLELINKTITLE'></ELEMENT>
		<ELEMENT NAME='ARTICLEFORUMSTYLE'></ELEMENT>
		<ELEMENT NAME='POLLTYPE1'></ELEMENT>
					
		<ELEMENT NAME='DATECREATED' EI='add'></ELEMENT>
		<ELEMENT NAME='LASTUPDATED' EI='add'></ELEMENT>
		<ELEMENT NAME='AUTHORNAME' EI='add'></ELEMENT>
		<ELEMENT NAME='AUTHORUSERID' EI='add'></ELEMENT>
		<ELEMENT NAME='AUTHORUSERNAME' EI='add'></ELEMENT>
		
		<ELEMENT NAME='TYPEOFARTICLE' EI='add' ACTION='KEYPHRASE'></ELEMENT>
		<ELEMENT NAME='SPORT' EI='add' ACTION='KEYPHRASE'><VALIDATE TYPE='EMPTY'/></ELEMENT>
		<ELEMENT NAME='OTHERSPORT' EI='add'  ACTION='KEYPHRASE'></ELEMENT>
		<ELEMENT NAME='OTHERSPORTUSERS' EI='add'  ACTION='KEYPHRASE'></ELEMENT>
		<ELEMENT NAME='COMPETITION' EI='add' ACTION='KEYPHRASE'></ELEMENT>
		<ELEMENT NAME='OTHERCOMPETITION' EI='add'  ACTION='KEYPHRASE'></ELEMENT>
		<ELEMENT NAME='TEAM' EI='add' ACTION='KEYPHRASE'><VALIDATE TYPE='EMPTY'/></ELEMENT>
		<ELEMENT NAME='OTHERTEAM' EI='add'  ACTION='KEYPHRASE'></ELEMENT>
		<ELEMENT NAME='MANAGERSPICK' EI='add' ACTION='KEYPHRASE'></ELEMENT>
		
		<ELEMENT NAME='AUTOCOMPETITIONS' ACTION='KEYPHRASE'></ELEMENT>
		<ELEMENT NAME='AUTONAMES' ACTION='KEYPHRASE'></ELEMENT>
	</MULTI-INPUT>]]>
</xsl:variable>

<xsl:variable name="editorial_article_fields">
	<![CDATA[<MULTI-INPUT>
		<REQUIRED NAME='TYPE'></REQUIRED>
		<REQUIRED NAME='BODY'><VALIDATE TYPE='EMPTY'/></REQUIRED>
		<REQUIRED NAME='TITLE'><VALIDATE TYPE='EMPTY'/></REQUIRED>
		<ELEMENT NAME='DATECREATED' EI='add'></ELEMENT>
		
		<ELEMENT NAME='INTROTEXT' EI='add'></ELEMENT>
		
		<ELEMENT NAME='DATECREATED' EI='add'></ELEMENT>
		<ELEMENT NAME='LASTUPDATED' EI='add'></ELEMENT>
		<ELEMENT NAME='AUTHORNAME' EI='add'></ELEMENT>
		<ELEMENT NAME='AUTHORUSERID' EI='add'></ELEMENT>
		<ELEMENT NAME='AUTHORUSERNAME' EI='add'></ELEMENT>
	</MULTI-INPUT>]]>
</xsl:variable>

<xsl:variable name="popup_article_fields">
	<![CDATA[<MULTI-INPUT>
		<REQUIRED NAME='TYPE'></REQUIRED>
		<REQUIRED NAME='BODY'><VALIDATE TYPE='EMPTY'/></REQUIRED>
		<REQUIRED NAME='TITLE'><VALIDATE TYPE='EMPTY'/></REQUIRED>
		<ELEMENT NAME='DATECREATED' EI='add'></ELEMENT>
		
		<ELEMENT NAME='DATECREATED' EI='add'></ELEMENT>
		<ELEMENT NAME='LASTUPDATED' EI='add'></ELEMENT>
		<ELEMENT NAME='AUTHORNAME' EI='add'></ELEMENT>
		<ELEMENT NAME='AUTHORUSERID' EI='add'></ELEMENT>
		<ELEMENT NAME='AUTHORUSERNAME' EI='add'></ELEMENT>
	</MULTI-INPUT>]]>
</xsl:variable>
</xsl:stylesheet>
